## TRANSFORMACIÓN Y LIMPIEZA DE LA DATA

En esta parte centraremos nuestra atención en la limpieza y transformación de la data proveida por la dirección del departamento de analisis de datos junto con datos adicionales obtenidos desde otras fuentes externas.

### I. IMPORTAMOS LAS LIBRERIAS A UTILIZAR

In [3]:
import pandas as pd
import numpy as np

### II. IMPORTAMOS NUESTRA DATA

#### A. COMENZAREMOS CON LA LIMPIEZA DE LOS DATOS CORRESPONDIENTES A LA EMPRESA COURSERA

1.- IMPORTAMOS LA DATA DEL ARCHIVO Coursera_courses.csv

In [2]:
#Definimos el dataframe df_coursera para visualizar los datos del archivo coursera_courses.csv
df_coursera = pd.read_csv('Coursera_courses.csv', sep=',')

In [3]:
#Visualizamos nuestro dataframe
df_coursera

name  \
0                                     Machine Learning   
1                                    Indigenous Canada   
2                            The Science of Well-Being   
3                       Technical Support Fundamentals   
4    Become a CBRS Certified Professional Installer...   
..                                                 ...   
618              Accounting Data Analytics with Python   
619             Introduction to Molecular Spectroscopy   
620                                Managing as a Coach   
621             The fundamentals of hotel distribution   
622                     A Crash Course in Data Science   

                                    institution  \
0                           Stanford University   
1                         University of Alberta   
2                               Yale University   
3                                        Google   
4                     Google - Spectrum Sharing   
..                                          ...   
618  University of Illinois at Urbana-Champaign   
619                 University of Manchester      
620             University of California, Davis   
621                       ESSEC Business School   
622                    Johns Hopkins University   

                                            course_url  \
0      https://www.coursera.org/learn/machine-learning   
1     https://www.coursera.org/learn/indigenous-canada   
2    https://www.coursera.org/learn/the-science-of-...   
3    https://www.coursera.org/learn/technical-suppo...   
4    https://www.coursera.org/learn/google-cbrs-cpi...   
..                                                 ...   
618  https://www.coursera.org/learn/accounting-data...   
619        https://www.coursera.org/learn/spectroscopy   
620  https://www.coursera.org/learn/managing-as-a-c...   
621  https://www.coursera.org/learn/hotel-distribution   
622  https://www.coursera.org/learn/data-science-co...   

                            course_id  
0                    machine-learning  
1                   indigenous-canada  
2           the-science-of-well-being  
3      technical-support-fundamentals  
4            google-cbrs-cpi-training  
..                                ...  
618  accounting-data-analytics-python  
619                      spectroscopy  
620               managing-as-a-coach  
621                hotel-distribution  
622               data-science-course  

[623 rows x 4 columns]

In [4]:
#Veamos la información de los datos
df_coursera.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   name         623 non-null    object
 1   institution  623 non-null    object
 2   course_url   623 non-null    object
 3   course_id    623 non-null    object
dtypes: object(4)
memory usage: 19.6+ KB


In [5]:
#Verificamos si hay valores duplicados
df_coursera.duplicated().value_counts()

False    623
dtype: int64

OBS: En una primera inspección de los datos observamos que el dataframe consta de cuatro columnas y 623 filas donde ninguna es de valor tipo nulo y tampoco hay duplicados, además podemos ver que la columna course_url contiene información de las direcciones url correspondiente de cada curso, sin embargo consideramos que para nuestro análisis no será necesario.

In [6]:
#Procedemos a eliminar la columna correspondiente a las url
df_coursera.drop(columns='course_url', inplace=True)

In [7]:
#Visualizamos
df_coursera

name  \
0                                     Machine Learning   
1                                    Indigenous Canada   
2                            The Science of Well-Being   
3                       Technical Support Fundamentals   
4    Become a CBRS Certified Professional Installer...   
..                                                 ...   
618              Accounting Data Analytics with Python   
619             Introduction to Molecular Spectroscopy   
620                                Managing as a Coach   
621             The fundamentals of hotel distribution   
622                     A Crash Course in Data Science   

                                    institution  \
0                           Stanford University   
1                         University of Alberta   
2                               Yale University   
3                                        Google   
4                     Google - Spectrum Sharing   
..                                          ...   
618  University of Illinois at Urbana-Champaign   
619                 University of Manchester      
620             University of California, Davis   
621                       ESSEC Business School   
622                    Johns Hopkins University   

                            course_id  
0                    machine-learning  
1                   indigenous-canada  
2           the-science-of-well-being  
3      technical-support-fundamentals  
4            google-cbrs-cpi-training  
..                                ...  
618  accounting-data-analytics-python  
619                      spectroscopy  
620               managing-as-a-coach  
621                hotel-distribution  
622               data-science-course  

[623 rows x 3 columns]

IMPORTANTE: 
Debido a que esta base de datos proveída por la dirección del área de datos no es suficiente para nuestro estudio, decidí no utilizarla y en su lugar utilizar otra data mucho más completa y con mayor cantidad de información del sitio publico de datos Kaggle de nombre Coursera_courses.csv también. 

2.- IMPORTAMOS LA DATA DEL ARCHIVO UCoursera_Courses.csv

Esta data fué obtenida de el sitio web de bases de datos Kaggle y corresponde a una colaboración de un analista de datos parte de la comunidad que mediante técnicas de web scraping realizó una recolección de datos en el año 2021, esta data tiene mayor cantidad de información y complementa nuestra data anterior ya que contiene información hasta el año 2020.

In [35]:
#Creamos nuestro dataframe de nombre df_coursera_scrap
df_coursera_scrap = pd.read_csv('./Datos adicionales/coursera/UCoursera_Courses.csv', sep=',')

In [36]:
#Visualizamos
df_coursera_scrap

Unnamed: 0                                       course_title  \
0           134  (ISC)² Systems Security Certified Practitioner...   
1           743  A Crash Course in Causality:  Inferring Causal...   
2           874                     A Crash Course in Data Science   
3           413                            A Law Student's Toolkit   
4           635                A Life of Happiness and Fulfillment   
..          ...                                                ...   
886         236                         Программирование на Python   
887         883               Психолингвистика (Psycholinguistics)   
888         545       Разработка интерфейсов: вёрстка и JavaScript   
889         875                            Русский как иностранный   
890         163      Финансовые инструменты для частного инвестора   

                                   course_organization  \
0                                               (ISC)²   
1                           University of Pennsylvania   
2                             Johns Hopkins University   
3                                      Yale University   
4                            Indian School of Business   
..                                                 ...   
886                                      Mail.Ru Group   
887                  Saint Petersburg State University   
888                        E-Learning Development Fund   
889                  Saint Petersburg State University   
890  National Research University Higher School of ...   

    course_Certificate_type  course_rating course_difficulty  \
0            SPECIALIZATION            4.7          Beginner   
1                    COURSE            4.7      Intermediate   
2                    COURSE            4.5             Mixed   
3                    COURSE            4.7             Mixed   
4                    COURSE            4.8             Mixed   
..                      ...            ...               ...   
886          SPECIALIZATION            4.5      Intermediate   
887                  COURSE            4.8             Mixed   
888          SPECIALIZATION            4.5      Intermediate   
889          SPECIALIZATION            4.6      Intermediate   
890          SPECIALIZATION            4.7          Beginner   

    course_students_enrolled  
0                       5.3k  
1                        17k  
2                       130k  
3                        91k  
4                       320k  
..                       ...  
886                      52k  
887                      21k  
888                      30k  
889                     9.8k  
890                      38k  

[891 rows x 7 columns]

In [37]:
#Veamos la información de los datos
df_coursera_scrap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                891 non-null    int64  
 1   course_title              891 non-null    object 
 2   course_organization       891 non-null    object 
 3   course_Certificate_type   891 non-null    object 
 4   course_rating             891 non-null    float64
 5   course_difficulty         891 non-null    object 
 6   course_students_enrolled  891 non-null    object 
dtypes: float64(1), int64(1), object(5)
memory usage: 48.9+ KB


In [38]:
#Verificamos filas duplicadas
df_coursera_scrap.duplicated().value_counts()

False    891
dtype: int64

OBS: En una primera inspección de los datos vemos que no necesitamos la columna Unnamed: 0, el tipo de dato de la columna course_students_enrolled no es el correcto, los valores de la columna course_Certificate_type estan en mayúsculas y debemos cambiarlos a minúsculas.

In [39]:
#Eliminamos la primera columna
df_coursera_scrap = df_coursera_scrap.drop(columns='Unnamed: 0')

In [40]:
#Cambianos las filas con valores en mayúsculas
df_coursera_scrap['course_Certificate_type'] = df_coursera_scrap['course_Certificate_type'].str.capitalize()

OBS: La columna course_students_enrolled tiene letras k y m que representan miles y millones por lo que debemos realizar una multiplicacion para cada caso.

In [41]:
#Expresamos la columna a valores numericos sin strings
df_coursera_scrap['course_students_enrolled'] = df_coursera_scrap['course_students_enrolled'].apply(lambda x: float(x.replace('k', '')) * 1000 if 'k' in x else (float(x.replace('m', '')) * 1000000 if 'm' in x else float(x)))

In [42]:
#Visualizamos
df_coursera_scrap

course_title  \
0    (ISC)² Systems Security Certified Practitioner...   
1    A Crash Course in Causality:  Inferring Causal...   
2                       A Crash Course in Data Science   
3                              A Law Student's Toolkit   
4                  A Life of Happiness and Fulfillment   
..                                                 ...   
886                         Программирование на Python   
887               Психолингвистика (Psycholinguistics)   
888       Разработка интерфейсов: вёрстка и JavaScript   
889                            Русский как иностранный   
890      Финансовые инструменты для частного инвестора   

                                   course_organization  \
0                                               (ISC)²   
1                           University of Pennsylvania   
2                             Johns Hopkins University   
3                                      Yale University   
4                            Indian School of Business   
..                                                 ...   
886                                      Mail.Ru Group   
887                  Saint Petersburg State University   
888                        E-Learning Development Fund   
889                  Saint Petersburg State University   
890  National Research University Higher School of ...   

    course_Certificate_type  course_rating course_difficulty  \
0            Specialization            4.7          Beginner   
1                    Course            4.7      Intermediate   
2                    Course            4.5             Mixed   
3                    Course            4.7             Mixed   
4                    Course            4.8             Mixed   
..                      ...            ...               ...   
886          Specialization            4.5      Intermediate   
887                  Course            4.8             Mixed   
888          Specialization            4.5      Intermediate   
889          Specialization            4.6      Intermediate   
890          Specialization            4.7          Beginner   

     course_students_enrolled  
0                      5300.0  
1                     17000.0  
2                    130000.0  
3                     91000.0  
4                    320000.0  
..                        ...  
886                   52000.0  
887                   21000.0  
888                   30000.0  
889                    9800.0  
890                   38000.0  

[891 rows x 6 columns]

In [43]:
#Cambiamos el tipo de dato de la columna course_students a entero
df_coursera_scrap['course_students_enrolled'] = df_coursera_scrap['course_students_enrolled'].astype('Int64')

In [44]:
#Visualizamos
df_coursera_scrap

course_title  \
0    (ISC)² Systems Security Certified Practitioner...   
1    A Crash Course in Causality:  Inferring Causal...   
2                       A Crash Course in Data Science   
3                              A Law Student's Toolkit   
4                  A Life of Happiness and Fulfillment   
..                                                 ...   
886                         Программирование на Python   
887               Психолингвистика (Psycholinguistics)   
888       Разработка интерфейсов: вёрстка и JavaScript   
889                            Русский как иностранный   
890      Финансовые инструменты для частного инвестора   

                                   course_organization  \
0                                               (ISC)²   
1                           University of Pennsylvania   
2                             Johns Hopkins University   
3                                      Yale University   
4                            Indian School of Business   
..                                                 ...   
886                                      Mail.Ru Group   
887                  Saint Petersburg State University   
888                        E-Learning Development Fund   
889                  Saint Petersburg State University   
890  National Research University Higher School of ...   

    course_Certificate_type  course_rating course_difficulty  \
0            Specialization            4.7          Beginner   
1                    Course            4.7      Intermediate   
2                    Course            4.5             Mixed   
3                    Course            4.7             Mixed   
4                    Course            4.8             Mixed   
..                      ...            ...               ...   
886          Specialization            4.5      Intermediate   
887                  Course            4.8             Mixed   
888          Specialization            4.5      Intermediate   
889          Specialization            4.6      Intermediate   
890          Specialization            4.7          Beginner   

     course_students_enrolled  
0                        5300  
1                       17000  
2                      130000  
3                       91000  
4                      320000  
..                        ...  
886                     52000  
887                     21000  
888                     30000  
889                      9800  
890                     38000  

[891 rows x 6 columns]

In [45]:
#Visualizamos la información de la data
df_coursera_scrap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   course_title              891 non-null    object 
 1   course_organization       891 non-null    object 
 2   course_Certificate_type   891 non-null    object 
 3   course_rating             891 non-null    float64
 4   course_difficulty         891 non-null    object 
 5   course_students_enrolled  891 non-null    Int64  
dtypes: Int64(1), float64(1), object(4)
memory usage: 42.8+ KB


In [233]:
#Vamos a seleccionar algunas columnas de nuestro dataframe, para unirlos más adelante
data_for_join1 = df_coursera_scrap[['course_title', 'course_organization', 'course_rating', 'course_difficulty']]

In [234]:
data_for_join1

course_title  \
0    (ISC)² Systems Security Certified Practitioner...   
1    A Crash Course in Causality:  Inferring Causal...   
2                       A Crash Course in Data Science   
3                              A Law Student's Toolkit   
4                  A Life of Happiness and Fulfillment   
..                                                 ...   
886                         Программирование на Python   
887               Психолингвистика (Psycholinguistics)   
888       Разработка интерфейсов: вёрстка и JavaScript   
889                            Русский как иностранный   
890      Финансовые инструменты для частного инвестора   

                                   course_organization  course_rating  \
0                                               (ISC)²            4.7   
1                           University of Pennsylvania            4.7   
2                             Johns Hopkins University            4.5   
3                                      Yale University            4.7   
4                            Indian School of Business            4.8   
..                                                 ...            ...   
886                                      Mail.Ru Group            4.5   
887                  Saint Petersburg State University            4.8   
888                        E-Learning Development Fund            4.5   
889                  Saint Petersburg State University            4.6   
890  National Research University Higher School of ...            4.7   

    course_difficulty  
0            Beginner  
1        Intermediate  
2               Mixed  
3               Mixed  
4               Mixed  
..                ...  
886      Intermediate  
887             Mixed  
888      Intermediate  
889      Intermediate  
890          Beginner  

[891 rows x 4 columns]

4.- IMPORTAMOS LA DATA DEL ARCHIVO Coursera_courses.csv

Esta data también fué obtenida de el sitio web de bases de datos Kaggle y corresponde a una colaboración de un analista de datos parte de la comunidad que mediante técnicas de web scraping realizó una recolección de datos en el año 2021, esta información complementa nuestra data anterior.

In [132]:
#Importamos nuestro dataframe
df_coursera2 = pd.read_csv('./Datos adicionales/coursera/Coursera_courses.csv', sep=',')

In [133]:
#Visualizamos
df_coursera2

Unnamed: 0                                        course_name  \
0              0   Approve Social Media Posts with Zapier and Tr...   
1              1   Aprendizaje automático sin código: Azure ML D...   
2              2   Atención prehospitalaria del ictus agudo y se...   
3              3          Automate Blog Advertisements with Zapier    
4              4                      Bases de Datos NoSQL en Azure   
...          ...                                                ...   
6625        6625                   大學之理念 (The Idea of a University)   
6626        6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627        6627                                               天文探秘   
6628        6628     学会如何学习：帮助你掌握复杂学科的强大智力工具（Learning How to Learn）   
6629        6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type  \
0       Coursera Project Network  Split-screen video   
1       Coursera Project Network  Split-screen video   
2       Universitat de Barcelona         100% online   
3       Coursera Project Network  Split-screen video   
4       Coursera Project Network  Split-screen video   
...                          ...                 ...   
6625  National Taiwan University         100% online   
6626  National Taiwan University         100% online   
6627          Nanjing University         100% online   
6628                         NaN         100% online   
6629             Yale University         100% online   

                          duration        course_language course_rating  \
0                          2 hours                English      4.5stars   
1                          2 horas                Spanish      4.8stars   
2     Approx. 14 hours to complete                Spanish      4.9stars   
3                          2 hours                English      4.2stars   
4                          2 horas                Spanish      3.7stars   
...                            ...                    ...           ...   
6625  Approx. 16 hours to complete  Chinese (Traditional)      2.3stars   
6626  Approx. 18 hours to complete  Chinese (Traditional)      4.6stars   
6627  Approx. 18 hours to complete   Chinese (Simplified)      4.8stars   
6628  Approx. 20 hours to complete   Chinese (Simplified)      4.9stars   
6629  Approx. 39 hours to complete   Chinese (Simplified)      3.4stars   

                      course_level  \
0                         Beginner   
1                     Intermediate   
2               Intermediate Level   
3                     Intermediate   
4                         Beginner   
...                            ...   
6625                Beginner Level   
6626                Beginner Level   
6627  Approx. 18 hours to complete   
6628  Approx. 20 hours to complete   
6629  Approx. 39 hours to complete   

                                             instructor  \
0                                         Carmen Rojas,   
1                                          Leire Ahedo,   
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...   
3                                         Carmen Rojas,   
4                                          Leire Ahedo,   
...                                                 ...   
6625                                               黃俊傑,   
6626                                   魏志平,李正國,楊立偉,陳建錦,   
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,   
6628  Barbara Oakley,Dr. Terrence Sejnowski,Hong Che...   
6629                     Mary Evelyn Tucker ,John Grim,   

                                          course_detail  
0     The process that marketing and communications ...  
1     Este proyecto es un curso práctico y efectivo ...  
2     El ictus es una emergencia médica tiempo depen...  
3     Zapier is the industry leader in task automati...  
4     Este proyecto es un curso práctico y efectivo ...  
...                                                 ...  
6625  本

In [134]:
#Vemos la información de los datos
df_coursera2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6630 entries, 0 to 6629
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       6630 non-null   int64 
 1   course_name      6574 non-null   object
 2   university_name  6135 non-null   object
 3   course_type      6574 non-null   object
 4   duration         6565 non-null   object
 5   course_language  6574 non-null   object
 6   course_rating    6630 non-null   object
 7   course_level     6570 non-null   object
 8   instructor       6574 non-null   object
 9   course_detail    6574 non-null   object
dtypes: int64(1), object(9)
memory usage: 518.1+ KB


In [135]:
#Contabilizamos la cantidad de nulos
df_coursera2.isnull().sum()

Unnamed: 0           0
course_name         56
university_name    495
course_type         56
duration            65
course_language     56
course_rating        0
course_level        60
instructor          56
course_detail       56
dtype: int64

In [136]:
#Verificamos las filas duplicadas
df_coursera2.duplicated().value_counts()

False    6630
dtype: int64

OBS: En una primera observación vemos que la data tiene 10 columnas y 6630 filas, donde la primera hace referencia al índice del dataframe y no es necesario, además vemos que tenemos muchos valores nulos pero no tenemos filas duplicadas, debemos eliminar columnas que no consideramos necesarios para nuestro analisis además de darles el formato correcto a los datos y tambien el tipo de dato adecuado, también veo la posibilidad de renombrar las columnas.

In [137]:
#Comenzaremos eliminando columnas que no serán necesarios para nuestro analisis
df_coursera2 = df_coursera2.drop(columns=['Unnamed: 0', 'course_detail'])


In [138]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6628     学会如何学习：帮助你掌握复杂学科的强大智力工具（Learning How to Learn）   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type  \
0       Coursera Project Network  Split-screen video   
1       Coursera Project Network  Split-screen video   
2       Universitat de Barcelona         100% online   
3       Coursera Project Network  Split-screen video   
4       Coursera Project Network  Split-screen video   
...                          ...                 ...   
6625  National Taiwan University         100% online   
6626  National Taiwan University         100% online   
6627          Nanjing University         100% online   
6628                         NaN         100% online   
6629             Yale University         100% online   

                          duration        course_language course_rating  \
0                          2 hours                English      4.5stars   
1                          2 horas                Spanish      4.8stars   
2     Approx. 14 hours to complete                Spanish      4.9stars   
3                          2 hours                English      4.2stars   
4                          2 horas                Spanish      3.7stars   
...                            ...                    ...           ...   
6625  Approx. 16 hours to complete  Chinese (Traditional)      2.3stars   
6626  Approx. 18 hours to complete  Chinese (Traditional)      4.6stars   
6627  Approx. 18 hours to complete   Chinese (Simplified)      4.8stars   
6628  Approx. 20 hours to complete   Chinese (Simplified)      4.9stars   
6629  Approx. 39 hours to complete   Chinese (Simplified)      3.4stars   

                      course_level  \
0                         Beginner   
1                     Intermediate   
2               Intermediate Level   
3                     Intermediate   
4                         Beginner   
...                            ...   
6625                Beginner Level   
6626                Beginner Level   
6627  Approx. 18 hours to complete   
6628  Approx. 20 hours to complete   
6629  Approx. 39 hours to complete   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6628  Barbara Oakley,Dr. Terrence Sejnowski,Hong Che...  
6629                     Mary Evelyn Tucker ,John Grim,  

[6630 rows x 8 columns]

In [139]:
#Vemos que en nuestra columna course_rating, los numeros vienen acompñados de la palabra stars, procedemos a cambiarlo por un espacio
df_coursera2['course_rating'] = df_coursera2['course_rating'].str.replace('stars', '')


In [140]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6628     学会如何学习：帮助你掌握复杂学科的强大智力工具（Learning How to Learn）   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type  \
0       Coursera Project Network  Split-screen video   
1       Coursera Project Network  Split-screen video   
2       Universitat de Barcelona         100% online   
3       Coursera Project Network  Split-screen video   
4       Coursera Project Network  Split-screen video   
...                          ...                 ...   
6625  National Taiwan University         100% online   
6626  National Taiwan University         100% online   
6627          Nanjing University         100% online   
6628                         NaN         100% online   
6629             Yale University         100% online   

                          duration        course_language course_rating  \
0                          2 hours                English           4.5   
1                          2 horas                Spanish           4.8   
2     Approx. 14 hours to complete                Spanish           4.9   
3                          2 hours                English           4.2   
4                          2 horas                Spanish           3.7   
...                            ...                    ...           ...   
6625  Approx. 16 hours to complete  Chinese (Traditional)           2.3   
6626  Approx. 18 hours to complete  Chinese (Traditional)           4.6   
6627  Approx. 18 hours to complete   Chinese (Simplified)           4.8   
6628  Approx. 20 hours to complete   Chinese (Simplified)           4.9   
6629  Approx. 39 hours to complete   Chinese (Simplified)           3.4   

                      course_level  \
0                         Beginner   
1                     Intermediate   
2               Intermediate Level   
3                     Intermediate   
4                         Beginner   
...                            ...   
6625                Beginner Level   
6626                Beginner Level   
6627  Approx. 18 hours to complete   
6628  Approx. 20 hours to complete   
6629  Approx. 39 hours to complete   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6628  Barbara Oakley,Dr. Terrence Sejnowski,Hong Che...  
6629                     Mary Evelyn Tucker ,John Grim,  

[6630 rows x 8 columns]

In [168]:
#Vamos a eliminar los strings que acompañan a las horas, para dejar unicamente los números
df_coursera2['duration'] = df_coursera2['duration'].str.replace('Approx.', '')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('hours to complete', 'horas')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('hours', 'horas')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('horas', '')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('hour', '')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('Hour', '')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('one ', '1')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('heures', '')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('120 minutes', '2')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('2 s', '2')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('90 minutes', '1.5')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('ساعتين', '2')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('1  30 minutes', '1.5')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('1hr for project work', '1')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('[1] ', '1')
df_coursera2['duration'] = df_coursera2['duration'].str.replace('[\[\]]', '').str.strip()

C:\Users\Administrador\AppData\Local\Temp\ipykernel_18008\2455520753.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_coursera2['duration'] = df_coursera2['duration'].str.replace('Approx.', '')
C:\Users\Administrador\AppData\Local\Temp\ipykernel_18008\2455520753.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  df_coursera2['duration'] = df_coursera2['duration'].str.replace('[1] ', '1')


OBS: A pesar de realizar los reemplazos correspondientes en nuestra columna duration, notamos que esta tarea no termina ya que deben existir muchos datos de tipo string dentro de esta columna por lo que procederemos a ver que cantidad de datos son y ademas cual debe ser el valor que predomina para poder reemplazarlo de una forma más homogenea y definitiva.

In [210]:
#Visualizamos los datos no numericos en nuestra columna duration
non_numeric_values = df_coursera2[~df_coursera2['duration'].astype(str).str.isnumeric()]['duration'].unique()
non_numeric_values

array(['1.5',
       'About 60 minutes required for the project and 60 for the other materials (reading and assignment).',
       '1hr 40 mins', '1.25', '45 minutes', '90 min', '4 s', '55 minutes',
       '2.5', '3.5', '1hora', '60 minutos', '90 Minutes', '60 Minutes',
       '150 Minutes', '1Hora', 'Dos  aproximadamente', 'Dos',
       'Dos  aproximadamente.', '1ساعه', '1hr 40 minutes', '1to complete',
       'En total, 2', '1-1.5', '110 mins', '1and 10 minutes',
       '145 minutes', '1week of study, 2', '1.5 s', '130 minutes',
       '120 mins', '120 Minutes', '120 minutes', '120 Minutes.',
       '2  total', '65 minutes', '2 to 3', '105 minutes', '100 Minutes',
       '1hr 30m', '1hora y 50 minutos',
       '45 minutes for the guided part + 45 minutes for practice',
       '75-90mins', '80 minutes', '1hr 30 mins', '1hr 30 mts',
       '115 minutes', '1,5', 'una hora', '1and 35 minutes',
       '1and 30 minutes', '50 minutes', '2 , 15 minutes',
       'About 45 to 60  minutes', '45 

OBS: Aqui podemos ver que tenemos muchos valores donde en su mayoria ronda las dos horas  un poco mas o un poco menos por tanto procederemos a reemplazar todos estos valores por 2 horas.

In [211]:
#Procederemos a reemplazar de forma definitiva todos los valores string a 2 en nuestra columna duration
df_coursera2.loc[~df_coursera2['duration'].astype(str).str.isnumeric(), 'duration'] = '2'

In [215]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type duration  \
0       Coursera Project Network  Split-screen video        2   
1       Coursera Project Network  Split-screen video        2   
2       Universitat de Barcelona         100% online       14   
3       Coursera Project Network  Split-screen video        2   
4       Coursera Project Network  Split-screen video        2   
...                          ...                 ...      ...   
6624           Peking University         100% online       17   
6625  National Taiwan University         100% online       16   
6626  National Taiwan University         100% online       18   
6627          Nanjing University         100% online       18   
6629             Yale University         100% online       39   

            course_language  course_rating  course_level  \
0                   English            4.5      Beginner   
1                   Spanish            4.8  Intermediate   
2                   Spanish            4.9  Intermediate   
3                   English            4.2  Intermediate   
4                   Spanish            3.7      Beginner   
...                     ...            ...           ...   
6624   Chinese (Simplified)            4.3      Beginner   
6625  Chinese (Traditional)            2.3      Beginner   
6626  Chinese (Traditional)            4.6      Beginner   
6627   Chinese (Simplified)            4.8         Mixed   
6629   Chinese (Simplified)            3.4         Mixed   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6624                                                亓昕,  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6629                     Mary Evelyn Tucker ,John Grim,  

[6126 rows x 8 columns]

In [216]:
#Uniformizamos el nivel del curso a Beginner, Intermediate y Advanced
df_coursera2['course_level'] = df_coursera2['course_level'].str.replace('Beginner Level', 'Beginner')
df_coursera2['course_level'] = df_coursera2['course_level'].str.replace('Intermediate Level', 'Intermediate')
df_coursera2['course_level'] = df_coursera2['course_level'].str.replace('Advanced Level', 'Advanced')

In [217]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type duration  \
0       Coursera Project Network  Split-screen video        2   
1       Coursera Project Network  Split-screen video        2   
2       Universitat de Barcelona         100% online       14   
3       Coursera Project Network  Split-screen video        2   
4       Coursera Project Network  Split-screen video        2   
...                          ...                 ...      ...   
6624           Peking University         100% online       17   
6625  National Taiwan University         100% online       16   
6626  National Taiwan University         100% online       18   
6627          Nanjing University         100% online       18   
6629             Yale University         100% online       39   

            course_language  course_rating  course_level  \
0                   English            4.5      Beginner   
1                   Spanish            4.8  Intermediate   
2                   Spanish            4.9  Intermediate   
3                   English            4.2  Intermediate   
4                   Spanish            3.7      Beginner   
...                     ...            ...           ...   
6624   Chinese (Simplified)            4.3      Beginner   
6625  Chinese (Traditional)            2.3      Beginner   
6626  Chinese (Traditional)            4.6      Beginner   
6627   Chinese (Simplified)            4.8         Mixed   
6629   Chinese (Simplified)            3.4         Mixed   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6624                                                亓昕,  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6629                     Mary Evelyn Tucker ,John Grim,  

[6126 rows x 8 columns]

In [218]:
#Vemos que en la columna course_level aun tenemos filas donde no se ha indicado correctamente el nivel del curso, sino que se colocaron las horas de duracion
#Para corregir este problema reemplazaremos cualquier valor que no sea los definidos predefinidos en el paso anterior a Mixed
df_coursera2.loc[~df_coursera2['course_level'].isin(['Intermediate', 'Beginner', 'Advanced']), 'course_level'] = 'Mixed'

In [219]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type duration  \
0       Coursera Project Network  Split-screen video        2   
1       Coursera Project Network  Split-screen video        2   
2       Universitat de Barcelona         100% online       14   
3       Coursera Project Network  Split-screen video        2   
4       Coursera Project Network  Split-screen video        2   
...                          ...                 ...      ...   
6624           Peking University         100% online       17   
6625  National Taiwan University         100% online       16   
6626  National Taiwan University         100% online       18   
6627          Nanjing University         100% online       18   
6629             Yale University         100% online       39   

            course_language  course_rating  course_level  \
0                   English            4.5      Beginner   
1                   Spanish            4.8  Intermediate   
2                   Spanish            4.9  Intermediate   
3                   English            4.2  Intermediate   
4                   Spanish            3.7      Beginner   
...                     ...            ...           ...   
6624   Chinese (Simplified)            4.3      Beginner   
6625  Chinese (Traditional)            2.3      Beginner   
6626  Chinese (Traditional)            4.6      Beginner   
6627   Chinese (Simplified)            4.8         Mixed   
6629   Chinese (Simplified)            3.4         Mixed   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6624                                                亓昕,  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6629                     Mary Evelyn Tucker ,John Grim,  

[6126 rows x 8 columns]

In [147]:
#Recordemos que nuestro dataframe tenia valores nulos, por lo que procedemos a borrar los valores nulos 
df_coursera2.dropna(inplace=True)

In [148]:
#Visualizamos
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type duration  \
0       Coursera Project Network  Split-screen video       2    
1       Coursera Project Network  Split-screen video       2    
2       Universitat de Barcelona         100% online      14    
3       Coursera Project Network  Split-screen video       2    
4       Coursera Project Network  Split-screen video       2    
...                          ...                 ...      ...   
6624           Peking University         100% online      17    
6625  National Taiwan University         100% online      16    
6626  National Taiwan University         100% online      18    
6627          Nanjing University         100% online      18    
6629             Yale University         100% online      39    

            course_language course_rating  course_level  \
0                   English           4.5      Beginner   
1                   Spanish           4.8  Intermediate   
2                   Spanish           4.9  Intermediate   
3                   English           4.2  Intermediate   
4                   Spanish           3.7      Beginner   
...                     ...           ...           ...   
6624   Chinese (Simplified)           4.3      Beginner   
6625  Chinese (Traditional)           2.3      Beginner   
6626  Chinese (Traditional)           4.6      Beginner   
6627   Chinese (Simplified)           4.8         Mixed   
6629   Chinese (Simplified)           3.4         Mixed   

                                             instructor  
0                                         Carmen Rojas,  
1                                          Leire Ahedo,  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                         Carmen Rojas,  
4                                          Leire Ahedo,  
...                                                 ...  
6624                                                亓昕,  
6625                                               黃俊傑,  
6626                                   魏志平,李正國,楊立偉,陳建錦,  
6627                                 施勇,谢懿,陈鹏飞,李向东,周济林,  
6629                     Mary Evelyn Tucker ,John Grim,  

[6126 rows x 8 columns]

In [221]:
#Cambiamos el tipo de dato de las columnas duration y course_students
df_coursera2['duration'] = df_coursera2['duration'].astype('float64')
df_coursera2['course_rating'] = df_coursera2['course_rating'].astype('float64')

In [222]:
#Veamos la información de nuestro dataframe
df_coursera2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6126 entries, 0 to 6629
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   course_name      6126 non-null   object 
 1   university_name  6126 non-null   object 
 2   course_type      6126 non-null   object 
 3   duration         6126 non-null   float64
 4   course_language  6126 non-null   object 
 5   course_rating    6126 non-null   float64
 6   course_level     6126 non-null   object 
 7   instructor       6126 non-null   object 
dtypes: float64(2), object(6)
memory usage: 430.7+ KB


In [223]:
#Eliminamos la última coma de los nombres de los instructores
df_coursera2['instructor'] = df_coursera2['instructor'].str.rsplit(',', 1).str[0]


C:\Users\Administrador\AppData\Local\Temp\ipykernel_18008\1410889172.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  df_coursera2['instructor'] = df_coursera2['instructor'].str.rsplit(',', 1).str[0]


In [224]:
df_coursera2

course_name  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

                 university_name         course_type  duration  \
0       Coursera Project Network  Split-screen video       2.0   
1       Coursera Project Network  Split-screen video       2.0   
2       Universitat de Barcelona         100% online      14.0   
3       Coursera Project Network  Split-screen video       2.0   
4       Coursera Project Network  Split-screen video       2.0   
...                          ...                 ...       ...   
6624           Peking University         100% online      17.0   
6625  National Taiwan University         100% online      16.0   
6626  National Taiwan University         100% online      18.0   
6627          Nanjing University         100% online      18.0   
6629             Yale University         100% online      39.0   

            course_language  course_rating  course_level  \
0                   English            4.5      Beginner   
1                   Spanish            4.8  Intermediate   
2                   Spanish            4.9  Intermediate   
3                   English            4.2  Intermediate   
4                   Spanish            3.7      Beginner   
...                     ...            ...           ...   
6624   Chinese (Simplified)            4.3      Beginner   
6625  Chinese (Traditional)            2.3      Beginner   
6626  Chinese (Traditional)            4.6      Beginner   
6627   Chinese (Simplified)            4.8         Mixed   
6629   Chinese (Simplified)            3.4         Mixed   

                                             instructor  
0                                          Carmen Rojas  
1                                           Leire Ahedo  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                          Carmen Rojas  
4                                           Leire Ahedo  
...                                                 ...  
6624                                                 亓昕  
6625                                                黃俊傑  
6626                                    魏志平,李正國,楊立偉,陳建錦  
6627                                  施勇,谢懿,陈鹏飞,李向东,周济林  
6629                      Mary Evelyn Tucker ,John Grim  

[6126 rows x 8 columns]

In [245]:
#Vamos a renombrar algunas columnas
df_coursera2.rename(columns={'course_name': 'course_title', 'university_name': 'course_organization', 'course_level': 'course_difficulty', 'duration': 'duration(h)'}, inplace=True)

In [246]:
df_coursera2

course_title  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

             course_organization         course_type  duration(h)  \
0       Coursera Project Network  Split-screen video          2.0   
1       Coursera Project Network  Split-screen video          2.0   
2       Universitat de Barcelona         100% online         14.0   
3       Coursera Project Network  Split-screen video          2.0   
4       Coursera Project Network  Split-screen video          2.0   
...                          ...                 ...          ...   
6624           Peking University         100% online         17.0   
6625  National Taiwan University         100% online         16.0   
6626  National Taiwan University         100% online         18.0   
6627          Nanjing University         100% online         18.0   
6629             Yale University         100% online         39.0   

            course_language  course_rating course_difficulty  \
0                   English            4.5          Beginner   
1                   Spanish            4.8      Intermediate   
2                   Spanish            4.9      Intermediate   
3                   English            4.2      Intermediate   
4                   Spanish            3.7          Beginner   
...                     ...            ...               ...   
6624   Chinese (Simplified)            4.3          Beginner   
6625  Chinese (Traditional)            2.3          Beginner   
6626  Chinese (Traditional)            4.6          Beginner   
6627   Chinese (Simplified)            4.8             Mixed   
6629   Chinese (Simplified)            3.4             Mixed   

                                             instructor  
0                                          Carmen Rojas  
1                                           Leire Ahedo  
2     Montse Gorchs Molist,Natalia Perez de la Ossa,...  
3                                          Carmen Rojas  
4                                           Leire Ahedo  
...                                                 ...  
6624                                                 亓昕  
6625                                                黃俊傑  
6626                                    魏志平,李正國,楊立偉,陳建錦  
6627                                  施勇,谢懿,陈鹏飞,李向东,周济林  
6629                      Mary Evelyn Tucker ,John Grim  

[6126 rows x 8 columns]

OBS: A continuación seleccionaremos cuatro columnas de nuestro dataframe para posteriormente unirlo con nuestro dataframe final de nuestro archivo inicial

In [230]:
#Seleccionamos las columnas necesarias para unir nuestros dataframe
data_for_join2 = df_coursera2[['course_title', 'course_organization', 'course_rating', 'course_difficulty']]

In [231]:
#Visualizamos
data_for_join2

course_title  \
0      Approve Social Media Posts with Zapier and Tr...   
1      Aprendizaje automático sin código: Azure ML D...   
2      Atención prehospitalaria del ictus agudo y se...   
3             Automate Blog Advertisements with Zapier    
4                         Bases de Datos NoSQL en Azure   
...                                                 ...   
6624                                              大学生瑜伽   
6625                   大學之理念 (The Idea of a University)   
6626  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
6627                                               天文探秘   
6629  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

             course_organization  course_rating course_difficulty  
0       Coursera Project Network            4.5          Beginner  
1       Coursera Project Network            4.8      Intermediate  
2       Universitat de Barcelona            4.9      Intermediate  
3       Coursera Project Network            4.2      Intermediate  
4       Coursera Project Network            3.7          Beginner  
...                          ...            ...               ...  
6624           Peking University            4.3          Beginner  
6625  National Taiwan University            2.3          Beginner  
6626  National Taiwan University            4.6          Beginner  
6627          Nanjing University            4.8             Mixed  
6629             Yale University            3.4             Mixed  

[6126 rows x 4 columns]

In [235]:
#Unimos los dataframes
df_merged = pd.concat([data_for_join1, data_for_join2], ignore_index=True)

In [236]:
#Visualizamos
df_merged

course_title  \
0     (ISC)² Systems Security Certified Practitioner...   
1     A Crash Course in Causality:  Inferring Causal...   
2                        A Crash Course in Data Science   
3                               A Law Student's Toolkit   
4                   A Life of Happiness and Fulfillment   
...                                                 ...   
7012                                              大学生瑜伽   
7013                   大學之理念 (The Idea of a University)   
7014  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
7015                                               天文探秘   
7016  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

             course_organization  course_rating course_difficulty  
0                         (ISC)²            4.7          Beginner  
1     University of Pennsylvania            4.7      Intermediate  
2       Johns Hopkins University            4.5             Mixed  
3                Yale University            4.7             Mixed  
4      Indian School of Business            4.8             Mixed  
...                          ...            ...               ...  
7012           Peking University            4.3          Beginner  
7013  National Taiwan University            2.3          Beginner  
7014  National Taiwan University            4.6          Beginner  
7015          Nanjing University            4.8             Mixed  
7016             Yale University            3.4             Mixed  

[7017 rows x 4 columns]

In [237]:
#Veamos si tenemos valores duplicados
df_merged.duplicated().value_counts()

False    6701
True      316
dtype: int64

OBS: Aqui podemos ver que tenemos 316 filas duplicadas, por lo que debemos eliminarlos.

In [238]:
#Eliminamos los duplicados
df_merged = df_merged.drop_duplicates(subset='course_title')


In [240]:
#Reiniciamos el indice 
#df_merged.reset_index(drop=True, inplace=True)
#Visualizamos la info de nuestra nueva data
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6533 entries, 0 to 7016
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         6533 non-null   object 
 1   course_organization  6533 non-null   object 
 2   course_rating        6533 non-null   float64
 3   course_difficulty    6533 non-null   object 
dtypes: float64(1), object(3)
memory usage: 255.2+ KB


In [241]:
#Visualizamos
df_merged

course_title  \
0     (ISC)² Systems Security Certified Practitioner...   
1     A Crash Course in Causality:  Inferring Causal...   
2                        A Crash Course in Data Science   
3                               A Law Student's Toolkit   
4                   A Life of Happiness and Fulfillment   
...                                                 ...   
7012                                              大学生瑜伽   
7013                   大學之理念 (The Idea of a University)   
7014  大數據分析：商業應用與策略管理 (Big Data Analytics: Business ...   
7015                                               天文探秘   
7016  宇宙之旅：对话 (Journey of the Universe: Weaving Know...   

             course_organization  course_rating course_difficulty  
0                         (ISC)²            4.7          Beginner  
1     University of Pennsylvania            4.7      Intermediate  
2       Johns Hopkins University            4.5             Mixed  
3                Yale University            4.7             Mixed  
4      Indian School of Business            4.8             Mixed  
...                          ...            ...               ...  
7012           Peking University            4.3          Beginner  
7013  National Taiwan University            2.3          Beginner  
7014  National Taiwan University            4.6          Beginner  
7015          Nanjing University            4.8             Mixed  
7016             Yale University            3.4             Mixed  

[6533 rows x 4 columns]

4.- EXPORTAMOS EN NUEVOS ARCHIVOS LOS DATAFRAMES OBTENIDOS

In [242]:
#Exportamos nuestra data que contiene información de los cursos hasta el año 2021
df_coursera_scrap.to_csv('completo_cant_estudiantes_800.csv', index=False)

In [247]:
df_coursera2.to_csv('completo_nocant_estudiantes_big.csv', index=False)

In [243]:
#Exportamos nuestra data con los cursos,organizacion y rating completo
df_merged.to_csv('curso_organizacion_rating_nivel_completo.csv', index=False)

#### B. COMENZAREMOS CON LA LIMPIEZA DE LOS DATOS CORRESPONDIENTES A LA EMPRESA EDX

1.- IMPORTAMOS LA DATA PROVEIDA POR LA DIRECCIÓN edx_courses.csv

In [276]:
#Importamos nuestra data y creamos nuestro dataframe
df_edx = pd.read_csv('edx_courses.csv', sep=',')

In [277]:
#Visualizamos
df_edx

title  \
0                                  How to Learn Online   
1    Programming for Everybody (Getting Started wit...   
2              CS50's Introduction to Computer Science   
3                                   The Analytics Edge   
4    Marketing Analytics: Marketing Measurement Str...   
..                                                 ...   
970  Leaders in Citizen Security and Justice Manage...   
971              Pattern Studying and Making | 图案审美与创作   
972  Computational Neuroscience: Neuronal Dynamics ...   
973  Cities and the Challenge of Sustainable Develo...   
974                      MathTrackX: Special Functions   

                                               summary n_enrolled  \
0    Learn essential strategies for successful onli...    124,980   
1    This course is a "no prerequisite" introductio...    293,864   
2    An introduction to the intellectual enterprise...  2,442,271   
3    Through inspiring examples and stories, discov...    129,555   
4       This course is part of a MicroMasters® Program     81,140   
..                                                 ...        ...   
970  Learn about the latest in prevention, police a...        NaN   
971  Fantastic experiences in beauty and its repres...        NaN   
972  This course explains the mathematical and comp...     11,246   
973  What is a sustainable city? Learn the basics h...      8,775   
974  Understand trigonometric, exponential and loga...        NaN   

                             course_type  \
0                Self-paced on your time   
1                Self-paced on your time   
2                Self-paced on your time   
3    Instructor-led on a course schedule   
4                Self-paced on your time   
..                                   ...   
970              Self-paced on your time   
971              Self-paced on your time   
972              Self-paced on your time   
973              Self-paced on your time   
974              Self-paced on your time   

                                  institution  \
0                                         edX   
1                  The University of Michigan   
2                          Harvard University   
3       Massachusetts Institute of Technology   
4          University of California, Berkeley   
..                                        ...   
970           Inter-American Development Bank   
971                       Tsinghua University   
972  École polytechnique fédérale de Lausanne   
973                               SDG Academy   
974                    University of Adelaide   

                                           instructors         Level  \
0              Nina Huntemann-Robyn Belair-Ben Piscopo  Introductory   
1                                    Charles Severance  Introductory   
2                   David J. Malan-Doug Lloyd-Brian Yu  Introductory   
3    Dimitris Bertsimas-Allison O'Hair-John Silberh...  Intermediate   
4                                       Stephan Sorger  Introductory   
..                                                 ...           ...   
970  Olga Espinoza-Eduardo Pazinato-Alejandra Mera-...  Intermediate   
971                                         Yuehua Nie  Introductory   
972                                   Wulfram Gerstner      Advanced   
973                                   Jeffrey D. Sachs  Introductory   
974                                    Dr David Butler  Introductory   

                          subject language    subtitles         course_effort  \
0    Education & Teacher Training  English      English    2–3 hours per week   
1                Computer Science  English      English    2–4 hours per week   
2                Computer Science  English      English   6–18 hours per week   
3      Data Analysis & Statistics  English      English  10–15 hours per week   
4                Computer Science  English      English    5–7 hours per week   
..                            ...      ...          ..

In [278]:
df_edx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   title               975 non-null    object
 1   summary             922 non-null    object
 2   n_enrolled          855 non-null    object
 3   course_type         975 non-null    object
 4   institution         975 non-null    object
 5   instructors         972 non-null    object
 6   Level               975 non-null    object
 7   subject             975 non-null    object
 8   language            975 non-null    object
 9   subtitles           972 non-null    object
 10  course_effort       975 non-null    object
 11  course_length       975 non-null    object
 12  price               975 non-null    object
 13  course_description  935 non-null    object
 14  course_syllabus     417 non-null    object
 15  course_url          975 non-null    object
dtypes: object(16)
memory usage

In [279]:
df_edx.isnull().sum()

title                   0
summary                53
n_enrolled            120
course_type             0
institution             0
instructors             3
Level                   0
subject                 0
language                0
subtitles               3
course_effort           0
course_length           0
price                   0
course_description     40
course_syllabus       558
course_url              0
dtype: int64

In [280]:
df_edx.duplicated().value_counts()

False    974
True       1
dtype: int64

OBS: En la primera inspección de esta data vemos que tenemos algunas columnas que no seran necesarias para nuestro estudio, la mayor cantidad de nulos esta en la columna course_syllabus, solo tenemos una fila duplicada, y necesitamos definir el tipo de dato necesario para las columnas con valores numéricos.

In [281]:
#Comenzaremos eliminando algunas columnas
df_edx.drop(columns=['summary', 'subtitles', 'course_description', 'course_syllabus', 'course_url'], inplace=True)

In [282]:
df_edx

title n_enrolled  \
0                                  How to Learn Online    124,980   
1    Programming for Everybody (Getting Started wit...    293,864   
2              CS50's Introduction to Computer Science  2,442,271   
3                                   The Analytics Edge    129,555   
4    Marketing Analytics: Marketing Measurement Str...     81,140   
..                                                 ...        ...   
970  Leaders in Citizen Security and Justice Manage...        NaN   
971              Pattern Studying and Making | 图案审美与创作        NaN   
972  Computational Neuroscience: Neuronal Dynamics ...     11,246   
973  Cities and the Challenge of Sustainable Develo...      8,775   
974                      MathTrackX: Special Functions        NaN   

                             course_type  \
0                Self-paced on your time   
1                Self-paced on your time   
2                Self-paced on your time   
3    Instructor-led on a course schedule   
4                Self-paced on your time   
..                                   ...   
970              Self-paced on your time   
971              Self-paced on your time   
972              Self-paced on your time   
973              Self-paced on your time   
974              Self-paced on your time   

                                  institution  \
0                                         edX   
1                  The University of Michigan   
2                          Harvard University   
3       Massachusetts Institute of Technology   
4          University of California, Berkeley   
..                                        ...   
970           Inter-American Development Bank   
971                       Tsinghua University   
972  École polytechnique fédérale de Lausanne   
973                               SDG Academy   
974                    University of Adelaide   

                                           instructors         Level  \
0              Nina Huntemann-Robyn Belair-Ben Piscopo  Introductory   
1                                    Charles Severance  Introductory   
2                   David J. Malan-Doug Lloyd-Brian Yu  Introductory   
3    Dimitris Bertsimas-Allison O'Hair-John Silberh...  Intermediate   
4                                       Stephan Sorger  Introductory   
..                                                 ...           ...   
970  Olga Espinoza-Eduardo Pazinato-Alejandra Mera-...  Intermediate   
971                                         Yuehua Nie  Introductory   
972                                   Wulfram Gerstner      Advanced   
973                                   Jeffrey D. Sachs  Introductory   
974                                    Dr David Butler  Introductory   

                          subject language         course_effort  \
0    Education & Teacher Training  English    2–3 hours per week   
1                Computer Science  English    2–4 hours per week   
2                Computer Science  English   6–18 hours per week   
3      Data Analysis & Statistics  English  10–15 hours per week   
4                Computer Science  English    5–7 hours per week   
..                            ...      ...                   ...   
970               Social Sciences  English    4–5 hours per week   
971                 Art & Culture       中文    3–5 hours per week   
972       Biology & Life Sciences  English    4–6 hours per week   
973         Environmental Studies  English    1–2 hours per week   
974                          Math  English    3–6 hours per week   

    course_length                                         price  
0         2 Weeks   FREE-Add a Verified Certificate for $49 USD  
1         7 Weeks   FREE-Add a Verified Certificate for $49 USD  
2        12 Weeks   FREE-Add a Verified Certificate for $90 USD  
3        13 Weeks  FREE-Add a Verified Certificate for $199 USD  
4         4 Weeks  FREE-Add a Verified Certificate for $249 USD  
..            ...       

In [283]:
#Verificamos la cantidad de nulos
df_edx.isnull().sum()

title              0
n_enrolled       120
course_type        0
institution        0
instructors        3
Level              0
subject            0
language           0
course_effort      0
course_length      0
price              0
dtype: int64

In [284]:
#Transformamos la forma en que aparecen los precios
df_edx['price'] = df_edx['price'].str.replace('FREE-Add a Verified Certificate for', '')
df_edx['price'] = df_edx['price'].str.replace('$', '')
df_edx['price'] = df_edx['price'].str.replace('USD', '')

C:\Users\Administrador\AppData\Local\Temp\ipykernel_12176\3027384005.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_edx['price'] = df_edx['price'].str.replace('$', '')


In [285]:
#Renombramos la columna precio señalando las unidades
df_edx.rename(columns={'price': 'price(USD)'}, inplace=True)

In [286]:
#Renombramos la columna course_length señalando las unidades
df_edx.rename(columns={'course_length': 'course_length(Weeks)'}, inplace=True)

In [287]:
#Eliminamos los la palabra Weerks de los valores de la columna course_length
df_edx['course_length(Weeks)'] = df_edx['course_length(Weeks)'].str.replace('Weeks', '')

In [288]:
#Reemplazamos los guiones por comas en la columna instructors
df_edx['instructors'] = df_edx['instructors'].str.replace('-', ', ')

In [289]:
#Reemplazamos el nivel introductory por beginner en la columna Level
df_edx['Level'] = df_edx['Level'].str.replace('Introductory', 'Beginner')

In [290]:
#Vemos que hay comas en los valores numericos de la columna n_enrolled procederemos a quitarlos
df_edx['n_enrolled'] = df_edx['n_enrolled'].str.replace(',', '')

In [298]:
#Cambiamos el tipo de dato a las columnas n_enrolled, course_length y price(USD)
df_edx['n_enrolled'] = df_edx['n_enrolled'].astype('int64')
df_edx['course_length(Weeks)'] = df_edx['course_length(Weeks)'].astype('int64')
df_edx['price(USD)'] = df_edx['price(USD)'].astype('float64')

In [292]:
#Vemos que aun tenemos 120 valores nulos en la columna n_enrolled
df_edx.isnull().sum()

title                     0
n_enrolled              120
course_type               0
institution               0
instructors               3
Level                     0
subject                   0
language                  0
course_effort             0
course_length(Weeks)      0
price(USD)                0
dtype: int64

In [293]:
#Calculamos la media de la columna n_enrolled 
df_edx['n_enrolled'].mean()

53260.350877192985

In [294]:
#Reemplazamos los valores nulos en la columna n_enrolled por la media
df_edx['n_enrolled'].fillna(53260, inplace=True)


In [296]:
#Visualizamos los cambios
df_edx.head()

title  n_enrolled  \
0                                How to Learn Online    124980.0   
1  Programming for Everybody (Getting Started wit...    293864.0   
2            CS50's Introduction to Computer Science   2442271.0   
3                                 The Analytics Edge    129555.0   
4  Marketing Analytics: Marketing Measurement Str...     81140.0   

                           course_type                            institution  \
0              Self-paced on your time                                    edX   
1              Self-paced on your time             The University of Michigan   
2              Self-paced on your time                     Harvard University   
3  Instructor-led on a course schedule  Massachusetts Institute of Technology   
4              Self-paced on your time     University of California, Berkeley   

                                         instructors         Level  \
0          Nina Huntemann, Robyn Belair, Ben Piscopo      Beginner   
1                                  Charles Severance      Beginner   
2               David J. Malan, Doug Lloyd, Brian Yu      Beginner   
3  Dimitris Bertsimas, Allison O'Hair, John Silbe...  Intermediate   
4                                     Stephan Sorger      Beginner   

                        subject language         course_effort  \
0  Education & Teacher Training  English    2–3 hours per week   
1              Computer Science  English    2–4 hours per week   
2              Computer Science  English   6–18 hours per week   
3    Data Analysis & Statistics  English  10–15 hours per week   
4              Computer Science  English    5–7 hours per week   

   course_length(Weeks)  price(USD)  
0                     2        49.0  
1                     7        49.0  
2                    12        90.0  
3                    13       199.0  
4                     4       249.0

In [299]:
df_edx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   title                 975 non-null    object 
 1   n_enrolled            975 non-null    int64  
 2   course_type           975 non-null    object 
 3   institution           975 non-null    object 
 4   instructors           972 non-null    object 
 5   Level                 975 non-null    object 
 6   subject               975 non-null    object 
 7   language              975 non-null    object 
 8   course_effort         975 non-null    object 
 9   course_length(Weeks)  975 non-null    int64  
 10  price(USD)            975 non-null    float64
dtypes: float64(1), int64(2), object(8)
memory usage: 83.9+ KB


In [302]:
#Veamos los lenguajes y su formato en la columna language
df_edx['language'].value_counts()

English          777
Español          176
Français           7
Italiano           4
中文                 4
Português          4
日本語                1
اللغة العربية      1
Deutsch            1
Name: language, dtype: int64

OBS: Podemos ver que el lenguaje no esta en español por lo que debemos reemplazar el idioma correspondiente en español.

In [303]:
#Vemos que los lenguajes no estan indicados en español y no estan homogenizados por lo que procedemos a reemplazar todos esos valores
df_edx['language'] = df_edx['language'].str.replace('中文', 'Chino')
df_edx['language'] = df_edx['language'].str.replace('Deutsch', 'Aleman')
df_edx['language'] = df_edx['language'].str.replace('日本語', 'Japones')
df_edx['language'] = df_edx['language'].str.replace('اللغة العربية', 'Arabe')
df_edx['language'] = df_edx['language'].str.replace('English', 'Ingles')
df_edx['language'] = df_edx['language'].str.replace('Français', 'Frances')
df_edx['language'] = df_edx['language'].str.replace('Português', 'Portugues')

In [304]:
#Veamos los lenguajes nuevamente
df_edx['language'].value_counts()

Ingles       777
Español      176
Frances        7
Italiano       4
Chino          4
Portugues      4
Japones        1
Arabe          1
Aleman         1
Name: language, dtype: int64

In [317]:
df_edx.head()

title  n_enrolled  \
0                                How to Learn Online      124980   
1  Programming for Everybody (Getting Started wit...      293864   
2            CS50's Introduction to Computer Science     2442271   
3                                 The Analytics Edge      129555   
4  Marketing Analytics: Marketing Measurement Str...       81140   

                           course_type                            institution  \
0              Self-paced on your time                                    edX   
1              Self-paced on your time             The University of Michigan   
2              Self-paced on your time                     Harvard University   
3  Instructor-led on a course schedule  Massachusetts Institute of Technology   
4              Self-paced on your time     University of California, Berkeley   

                                         instructors         Level  \
0          Nina Huntemann, Robyn Belair, Ben Piscopo      Beginner   
1                                  Charles Severance      Beginner   
2               David J. Malan, Doug Lloyd, Brian Yu      Beginner   
3  Dimitris Bertsimas, Allison O'Hair, John Silbe...  Intermediate   
4                                     Stephan Sorger      Beginner   

                        subject language         course_effort  \
0  Education & Teacher Training   Ingles    2–3 hours per week   
1              Computer Science   Ingles    2–4 hours per week   
2              Computer Science   Ingles   6–18 hours per week   
3    Data Analysis & Statistics   Ingles  10–15 hours per week   
4              Computer Science   Ingles    5–7 hours per week   

   course_length(Weeks)  price(USD)  
0                     2        49.0  
1                     7        49.0  
2                    12        90.0  
3                    13       199.0  
4                     4       249.0

In [307]:
#Creamos un nuevo dataframe que sera utilizado para unir con otra data tomando en cuenta columnas similares
data_for_join_edx = df_edx[['title', 'Level', 'course_effort', 'course_length(Weeks)', 'language','price(USD)', 'institution', 'n_enrolled']]

In [308]:
#Visualizamos
data_for_join_edx

title         Level  \
0                                  How to Learn Online      Beginner   
1    Programming for Everybody (Getting Started wit...      Beginner   
2              CS50's Introduction to Computer Science      Beginner   
3                                   The Analytics Edge  Intermediate   
4    Marketing Analytics: Marketing Measurement Str...      Beginner   
..                                                 ...           ...   
970  Leaders in Citizen Security and Justice Manage...  Intermediate   
971              Pattern Studying and Making | 图案审美与创作      Beginner   
972  Computational Neuroscience: Neuronal Dynamics ...      Advanced   
973  Cities and the Challenge of Sustainable Develo...      Beginner   
974                      MathTrackX: Special Functions      Beginner   

            course_effort  course_length(Weeks) language  price(USD)  \
0      2–3 hours per week                     2   Ingles        49.0   
1      2–4 hours per week                     7   Ingles        49.0   
2     6–18 hours per week                    12   Ingles        90.0   
3    10–15 hours per week                    13   Ingles       199.0   
4      5–7 hours per week                     4   Ingles       249.0   
..                    ...                   ...      ...         ...   
970    4–5 hours per week                    10   Ingles        25.0   
971    3–5 hours per week                    12    Chino       139.0   
972    4–6 hours per week                     6   Ingles       139.0   
973    1–2 hours per week                     1   Ingles        25.0   
974    3–6 hours per week                     4   Ingles        79.0   

                                  institution  n_enrolled  
0                                         edX      124980  
1                  The University of Michigan      293864  
2                          Harvard University     2442271  
3       Massachusetts Institute of Technology      129555  
4          University of California, Berkeley       81140  
..                                        ...         ...  
970           Inter-American Development Bank       53260  
971                       Tsinghua University       53260  
972  École polytechnique fédérale de Lausanne       11246  
973                               SDG Academy        8775  
974                    University of Adelaide       53260  

[975 rows x 8 columns]

2.- IMPORTAMOS LA DATA DEL ARCHIVO All_edx_courses_catalog.csv

Vamos a complementar el dataframe entregado por la dirección del área de datos con este dataframe obtenido de la sitio web de conjutos de datos Kaggle.

In [233]:
#Creamos nuestro dataframe a partir de nuestra data
df_edx2 = pd.read_csv('./Datos adicionales/edx/All_edx_courses_catalog.csv', sep=',')

In [234]:
#Visualizamos
df_edx2

Unnamed: 0                                        course_name  \
0              0                      The ArchitecturalImagination…   
1              1  The Path to Happiness:What Chinese PhilosophyT...   
2              2  Pyramids of Giza: AncientEgyptian Art andArcha...   
3              3  U.S. Public Policy: Social,Economic, and Forei...   
4              4     Women Making History:Ten Objects, ManyStories…   
...          ...                                                ...   
3077        3077          Introduction to DataAnalysis using Excel…   
3078        3078                       Data, Analytics andLearning…   
3079        3079            Statistics: Unlocking theWorld of Data…   
3080        3080            Biostatistics for Big DataApplications…   
3081        3081                        Essentials of DataLiteracy…   

                                             course_url  \
0     https://www.edx.org/course/the-architectural-i...   
1      https://www.edx.org/course/the-path-to-happiness   
2     https://www.edx.org/course/pyramids-of-giza-an...   
3     https://www.edx.org/course/us-public-policy-so...   
4     https://www.edx.org/course/women-making-histor...   
...                                                 ...   
3077  https://www.edx.org/course/introduction-to-dat...   
3078  https://www.edx.org/course/data-analytics-and-...   
3079  https://www.edx.org/course/statistics-unlockin...   
3080  https://www.edx.org/course/biostatistics-for-b...   
3081  https://www.edx.org/course/essentials-of-data-...   

                                           course_photo      course_level  \
0     https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
1     https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
2     https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
3     https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
4     https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
...                                                 ...               ...   
3077  https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
3078  https://prod-discovery.edx-cdn.org/media/cours...  ['Intermediate']   
3079  https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
3080  https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   
3081  https://prod-discovery.edx-cdn.org/media/cours...  ['Introductory']   

                 course_effort course_length course_language  \
0       ['3–5 hours per week']  ['10 Weeks']     ['English']   
1       ['1–2 hours per week']  ['13 Weeks']     ['English']   
2       ['2–4 hours per week']   ['8 Weeks']     ['English']   
3       ['2–4 hours per week']   ['4 Weeks']     ['English']   
4       ['2–3 hours per week']   ['8 Weeks']     ['English']   
...                        ...           ...             ...   
3077    ['2–4 hours per week']   ['4 Weeks']     ['English']   
3078                        []   ['4 Weeks']     ['English']   
3079    ['4–6 hours per week']   ['8 Weeks']     ['English']   
3080    ['2–3 hours per week']   ['8 Weeks']     ['English']   
3081  ['10–20 hours per week']   ['4 Weeks']     ['English']   

             course_subtitle  course_price  \
0                ['English']  ['$199 USD']   
1                ['English']   ['$99 USD']   
2                ['English']  ['$149 USD']   
3                ['English']   ['$99 USD']   
4                ['English']  ['$139 USD']   
...                      ...           ...   
3077             ['English']   ['$99 USD']   
3078  ['English', 'English']            []   
3079             ['English']   ['$49 USD']   
3080             ['English']   ['$49 USD']   
3081             ['English']   ['$99 USD']   

                                  course_partner  \
0                         ['Harvard University']   
1                         ['Harvard University']   
2                         ['Harvard Unive

In [235]:
#Verificamos la información de los datos
df_edx2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3082 entries, 0 to 3081
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          3082 non-null   int64 
 1   course_name         3082 non-null   object
 2   course_url          3082 non-null   object
 3   course_photo        3082 non-null   object
 4   course_level        3082 non-null   object
 5   course_effort       3082 non-null   object
 6   course_length       3082 non-null   object
 7   course_language     3082 non-null   object
 8   course_subtitle     3082 non-null   object
 9   course_price        3082 non-null   object
 10  course_partner      3082 non-null   object
 11  university_link     3082 non-null   object
 12  course_enrollments  3082 non-null   object
dtypes: int64(1), object(12)
memory usage: 313.1+ KB


In [236]:
#Verificamos si tenemos duplicados
df_edx2.duplicated().value_counts()

False    3082
dtype: int64

OBS: En nuestra primera inspección de los datos vemos que tenemos columnas que no aportaran a nuestro analisis, ademas de que en ciertas columnas los datos estan encerrados en una lista, el tipo de datos no es el adecuado en ciertas columnas, aparentemente no tenemos nulos y tampoco filas duplicadas, posiblemente sera necesario cambiar el nombre de algunas columnas.

In [237]:
#Eliminaremos algunas columnas de nuestro dataframe
df_edx2.drop(columns=['Unnamed: 0', 'course_photo', 'course_subtitle', 'university_link', 'course_url'], inplace=True)

In [238]:
#Si los datos en las columnas que tienen los valores encerrados en corchetes son listas procedemos a convertirlas en no listas
df_edx2 = df_edx2.explode(['course_level','course_effort', 'course_length', 'course_language', 'course_price', 'course_partner'])

In [239]:
#Visualizamos
df_edx2.head(3)

course_name      course_level  \
0                      The ArchitecturalImagination…  ['Introductory']   
1  The Path to Happiness:What Chinese PhilosophyT...  ['Introductory']   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  ['Introductory']   

            course_effort course_length course_language  course_price  \
0  ['3–5 hours per week']  ['10 Weeks']     ['English']  ['$199 USD']   
1  ['1–2 hours per week']  ['13 Weeks']     ['English']   ['$99 USD']   
2  ['2–4 hours per week']   ['8 Weeks']     ['English']  ['$149 USD']   

           course_partner course_enrollments  
0  ['Harvard University']            415,051  
1  ['Harvard University']             29,623  
2  ['Harvard University']            127,414

In [240]:
#Vemos que los datos aun continuan encerrados en corchetes, po lo que procedemos a eliminarlos
df_edx2['course_level'] = df_edx2['course_level'].str.strip('[]').str.replace('', '')
df_edx2['course_effort'] = df_edx2['course_effort'].str.strip('[]').str.replace('', '')
df_edx2['course_length'] = df_edx2['course_length'].str.strip('[]').str.replace('', '')
df_edx2['course_language'] = df_edx2['course_language'].str.strip('[]').str.replace('', '')
df_edx2['course_price'] = df_edx2['course_price'].str.strip('[]').str.replace('', '')
df_edx2['course_partner'] = df_edx2['course_partner'].str.strip('[]').str.replace('', '')

In [241]:
#Visualizamos
df_edx2.head(3)

course_name    course_level  \
0                      The ArchitecturalImagination…  'Introductory'   
1  The Path to Happiness:What Chinese PhilosophyT...  'Introductory'   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  'Introductory'   

          course_effort course_length course_language course_price  \
0  '3–5 hours per week'    '10 Weeks'       'English'   '$199 USD'   
1  '1–2 hours per week'    '13 Weeks'       'English'    '$99 USD'   
2  '2–4 hours per week'     '8 Weeks'       'English'   '$149 USD'   

         course_partner course_enrollments  
0  'Harvard University'            415,051  
1  'Harvard University'             29,623  
2  'Harvard University'            127,414

In [242]:
#Vemos que los datos estan encerrados en comillas simples, por lo que procedemos a eliminar las comillas
df_edx2['course_level'] = df_edx2['course_level'].str.strip('[]').str.replace("'", '')
df_edx2['course_effort'] = df_edx2['course_effort'].str.strip('[]').str.replace("'", '')
df_edx2['course_length'] = df_edx2['course_length'].str.strip('[]').str.replace("'", '')
df_edx2['course_language'] = df_edx2['course_language'].str.strip('[]').str.replace("'", '')
df_edx2['course_price'] = df_edx2['course_price'].str.strip('[]').str.replace("'", '')
df_edx2['course_partner'] = df_edx2['course_partner'].str.strip('[]').str.replace("'", '')

In [243]:
#Visualizamos
df_edx2.head(3)

course_name  course_level  \
0                      The ArchitecturalImagination…  Introductory   
1  The Path to Happiness:What Chinese PhilosophyT...  Introductory   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  Introductory   

        course_effort course_length course_language course_price  \
0  3–5 hours per week      10 Weeks         English     $199 USD   
1  1–2 hours per week      13 Weeks         English      $99 USD   
2  2–4 hours per week       8 Weeks         English     $149 USD   

       course_partner course_enrollments  
0  Harvard University            415,051  
1  Harvard University             29,623  
2  Harvard University            127,414

In [244]:
#Vamos a renombrar las columnas
df_edx2.rename(columns={'course_name': 'title', 'course_level': 'Level', 'course_length': 'course_length(Weeks)', 'course_language': 'language', 'course_price':'price(USD)', 'course_partner':'institution', 'course_enrollments':'n_enrolled' }, inplace=True)

In [245]:
#Visualizamos
df_edx2.head(3)

title         Level  \
0                      The ArchitecturalImagination…  Introductory   
1  The Path to Happiness:What Chinese PhilosophyT...  Introductory   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  Introductory   

        course_effort course_length(Weeks) language price(USD)  \
0  3–5 hours per week             10 Weeks  English   $199 USD   
1  1–2 hours per week             13 Weeks  English    $99 USD   
2  2–4 hours per week              8 Weeks  English   $149 USD   

          institution n_enrolled  
0  Harvard University    415,051  
1  Harvard University     29,623  
2  Harvard University    127,414

In [246]:
#Reemplazamos el nivel introductory por beginner en la columna Level
df_edx2['Level'] = df_edx2['Level'].str.replace('Introductory', 'Beginner')

In [247]:
#Verificamos los valores de nuestra columna Level
df_edx2['Level'].value_counts()

Beginner        1777
Intermediate     916
Advanced         384
                   5
Name: Level, dtype: int64

In [248]:
#Verificamos los valores de nuestra columna Language
df_edx2['n_enrolled'].value_counts()

not-mentioned    1818
5,334               3
16,442              2
16,729              2
10,308              2
                 ... 
55,288              1
94,549              1
7,267               1
69,681              1
25,537              1
Name: n_enrolled, Length: 1241, dtype: int64

In [249]:
#Verificamos los valores de nuestra columna Language
df_edx2['language'].value_counts()

English                                                                              2372
Español                                                                               386
中文                                                                                     79
Français                                                                               76
Italiano                                                                               52
Subject:Language, English                                                              32
Русский                                                                                18
Deutsch                                                                                14
                                                                                        6
日本語                                                                                     6
اللغة العربية                                                                           4
Nederlands

In [250]:
#Aqui podemos ver que algunas filas de las columnas estan vacíos pero no indicados con nulo.
fm = df_edx2[df_edx2['Level'] == '']
fm

title Level course_effort  \
1134             CS50's AP® ComputerScience Principles…                       
2473                               Retail Fundamentals…                       
2672         Business AnalyticsFundamentals forLeaders…                       
2747                         CorporateEntrepreneurship…                       
2766  AfricaLive! -Entrepreneurship inEmerging Econo...                       

     course_length(Weeks) language price(USD)    institution     n_enrolled  
1134                                           not-mentioned  not-mentioned  
2473                                                          not-mentioned  
2672                                                          not-mentioned  
2747                                                          not-mentioned  
2766                                                          not-mentioned

OBS: Aqui podemos ver que algunos valores en distintas columnas estan conformadas de vacio, también podemos ver que en nuestra columna n_enrolled tenemos el valor not-mentioned y que en la columna language no tenemos un valor definido claro para los lenguajes en algunas filas.

In [251]:
#Convertimos los valores vacíos a nulos
df_edx2 = df_edx2.replace('', np.nan)

In [252]:
#Calculamos la cantidad de nulos nuevamente
df_edx2.isnull().sum()

title                     0
Level                     5
course_effort           124
course_length(Weeks)     10
language                  6
price(USD)              136
institution               4
n_enrolled                0
dtype: int64

In [253]:
#Eliminamos los valores nulos 
df_edx2.dropna(inplace=True)

In [254]:
df_edx2.head()

title     Level  \
0                      The ArchitecturalImagination…  Beginner   
1  The Path to Happiness:What Chinese PhilosophyT...  Beginner   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  Beginner   
3  U.S. Public Policy: Social,Economic, and Forei...  Beginner   
4     Women Making History:Ten Objects, ManyStories…  Beginner   

        course_effort course_length(Weeks) language price(USD)  \
0  3–5 hours per week             10 Weeks  English   $199 USD   
1  1–2 hours per week             13 Weeks  English    $99 USD   
2  2–4 hours per week              8 Weeks  English   $149 USD   
3  2–4 hours per week              4 Weeks  English    $99 USD   
4  2–3 hours per week              8 Weeks  English   $139 USD   

          institution n_enrolled  
0  Harvard University    415,051  
1  Harvard University     29,623  
2  Harvard University    127,414  
3  Harvard University     46,472  
4  Harvard University     40,788

In [255]:
#Eliminamos los la palabra Weeks de los valores de la columna course_length
df_edx2['course_length(Weeks)'] = df_edx2['course_length(Weeks)'].str.replace(' Weeks', '')

In [274]:
#cambiamos el tipo de dato de la columna course_length(Weeks)
df_edx2['course_length(Weeks)'] = df_edx2['course_length(Weeks)'].astype('int64')

In [256]:
#Eliminamos el simbolo de dolar y la palabra USD de los precios
df_edx2['price(USD)'] = df_edx2['price(USD)'].str.replace('$', '')
df_edx2['price(USD)'] = df_edx2['price(USD)'].str.replace(' USD', '')

C:\Users\Administrador\AppData\Local\Temp\ipykernel_12176\1521082371.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_edx2['price(USD)'] = df_edx2['price(USD)'].str.replace('$', '')


In [257]:
#Vemos que hay comas en los valores numericos de la columna n_enrolled procederemos a quitarlos
df_edx2['n_enrolled'] = df_edx2['n_enrolled'].str.replace(',', '')

In [258]:
#Veamos nuestra data
df_edx2.head()

title     Level  \
0                      The ArchitecturalImagination…  Beginner   
1  The Path to Happiness:What Chinese PhilosophyT...  Beginner   
2  Pyramids of Giza: AncientEgyptian Art andArcha...  Beginner   
3  U.S. Public Policy: Social,Economic, and Forei...  Beginner   
4     Women Making History:Ten Objects, ManyStories…  Beginner   

        course_effort course_length(Weeks) language price(USD)  \
0  3–5 hours per week                   10  English        199   
1  1–2 hours per week                   13  English         99   
2  2–4 hours per week                    8  English        149   
3  2–4 hours per week                    4  English         99   
4  2–3 hours per week                    8  English        139   

          institution n_enrolled  
0  Harvard University     415051  
1  Harvard University      29623  
2  Harvard University     127414  
3  Harvard University      46472  
4  Harvard University      40788

In [259]:
#Recordemos que nuestra columna n_enrolled tenia valores string llamados not-mentioned, que cambiaremos a null
df_edx2['n_enrolled'] = df_edx2['n_enrolled'].replace('not-mentioned', np.nan)

In [300]:
#Cambiamos el tipo de dato de la columna n_enrolled
df_edx2['n_enrolled'] = df_edx2['n_enrolled'].astype('int64')

In [261]:
#Veamos las estadisticas de nuestra columna n_enrolled
df_edx2['n_enrolled'].describe().round(2)

count       1233.00
mean       45365.29
std       110992.53
min         5024.00
25%         9918.00
50%        19371.00
75%        44765.00
max      2522780.00
Name: n_enrolled, dtype: float64

In [262]:
#reemplazaremos los nulos de nuestra columna n_enrolled por la media
df_edx2['n_enrolled'] = df_edx2['n_enrolled'].fillna(45365)

In [263]:
#Vemos que hay comas en los valores numericos de la columna price(USD) procederemos a quitarlos
df_edx2['price(USD)'] = df_edx2['price(USD)'].str.replace(',', '')

In [264]:
#Cambiamos el tipo de dato de la columna price(USD)
df_edx2['price(USD)'] = df_edx2['price(USD)'].astype('float64')

OBS: Recordemos que en nuestra columna language los valores no tienen una respuesta homogenia en cuanto al lenguaje o esta escrito en otro idioma, por lo que tenemos que homogenizar los datos.

In [265]:
#Veamos la columna lenguaje
df_edx2['language'].value_counts()

English                                                                              2181
Español                                                                               374
Français                                                                               71
中文                                                                                     62
Italiano                                                                               52
Subject:Language, English                                                              31
Русский                                                                                18
Deutsch                                                                                14
日本語                                                                                     6
Subject:Language, English, Professional CertificateAmerican Sign Language Science       4
اللغة العربية                                                                           4
Português 

In [267]:
#Vemos que los lenguajes no estan indicados en español y no estan homogenizados por lo que procedemos a reemplazar todos esos valores
df_edx2['language'] = df_edx2['language'].str.replace('中文', 'Chino')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, English', 'English')
df_edx2['language'] = df_edx2['language'].str.replace('Русский', 'Ruso')
df_edx2['language'] = df_edx2['language'].str.replace('Deutsch', 'Aleman')
df_edx2['language'] = df_edx2['language'].str.replace('日本語', 'Japones')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, English, Professional CertificateAmerican Sign Language Science', 'English')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, Español', 'Español')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, Italiano', 'Italiano')
df_edx2['language'] = df_edx2['language'].str.replace('Nederlands', 'Holandes')
df_edx2['language'] = df_edx2['language'].str.replace('हिन्दी', 'Hindi')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, Русский', 'Ruso')
df_edx2['language'] = df_edx2['language'].str.replace('اللغة العربية', 'Arabe')
df_edx2['language'] = df_edx2['language'].str.replace('اردو', 'Urdu')
df_edx2['language'] = df_edx2['language'].str.replace('فارسی', 'Persa')
df_edx2['language'] = df_edx2['language'].str.replace('한국어', 'Coreano')
df_edx2['language'] = df_edx2['language'].str.replace('magyar', 'Hungaro')
df_edx2['language'] = df_edx2['language'].str.replace('Tiếng Việt', 'Vietnamita')
df_edx2['language'] = df_edx2['language'].str.replace('བོད་ཡིག', 'Tibetano')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, اللغة العربية', '')
df_edx2['language'] = df_edx2['language'].str.replace('English', 'Ingles')
df_edx2['language'] = df_edx2['language'].str.replace('Français', 'Frances')
df_edx2['language'] = df_edx2['language'].str.replace('Português', 'Portugues')
df_edx2['language'] = df_edx2['language'].str.replace('English, Professional CertificateAmerican Sign Language Science', 'Ingles')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, Ruso', 'Ruso')
df_edx2['language'] = df_edx2['language'].str.replace('Subject:Language, Arabe', 'Arabe')
df_edx2['language'] = df_edx2['language'].str.replace('Ingles, Professional CertificateAmerican Sign Language Science', 'Ingles')

In [272]:
#Veamos nuevamente la columna lenguaje
df_edx2['language'].value_counts()

Ingles        2216
Español        378
Frances         71
Chino           62
Italiano        55
Ruso            20
Aleman          14
Japones          6
Arabe            6
Portugues        4
Holandes         2
Hindi            2
Urdu             2
Coreano          1
Hungaro          1
Persa            1
Vietnamita       1
Tibetano         1
Name: language, dtype: int64

In [301]:
df_edx2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2843 entries, 0 to 3081
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   title                 2843 non-null   object 
 1   Level                 2843 non-null   object 
 2   course_effort         2843 non-null   object 
 3   course_length(Weeks)  2843 non-null   int64  
 4   language              2843 non-null   object 
 5   price(USD)            2843 non-null   float64
 6   institution           2843 non-null   object 
 7   n_enrolled            2843 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 199.9+ KB


OBS: Tenemos listos nuestros dataframe data_for_join_edx y df_edx2 para proceder con la union de los datos.

In [309]:
#Uniremos nuestros dataframe data_for_join_edx y df_edx2
df_edx_join = pd.concat([data_for_join_edx, df_edx2], ignore_index=True)

In [312]:
#Vemos la cantidad de columnas y filas resultantes de unir ambos dataframe
df_edx_join.shape

(3818, 8)

In [313]:
#Verificamos la cantidad de duplicados
df_edx_join.duplicated().value_counts()

False    3816
True        2
dtype: int64

In [314]:
#Eliminamos los duplicados
df_edx_join.drop_duplicates(inplace=True)

In [316]:
df_edx_join.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3816 entries, 0 to 3817
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   title                 3816 non-null   object 
 1   Level                 3816 non-null   object 
 2   course_effort         3816 non-null   object 
 3   course_length(Weeks)  3816 non-null   int64  
 4   language              3816 non-null   object 
 5   price(USD)            3816 non-null   float64
 6   institution           3816 non-null   object 
 7   n_enrolled            3816 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 268.3+ KB


In [320]:
#Vemos que en la columna principiantes tenemos valores en ingles el cual cambiaremos a español
reemplazos = {'Beginner': 'Principiante','Intermediate': 'Intermedio','Advanced': 'Avanzado','Mixed': 'Mixto'}
df_edx_join['Level'] = df_edx_join['Level'].replace(reemplazos)

In [321]:
#Visualizamos
df_edx_join

title         Level  \
0                                   How to Learn Online  Principiante   
1     Programming for Everybody (Getting Started wit...  Principiante   
2               CS50's Introduction to Computer Science  Principiante   
3                                    The Analytics Edge    Intermedio   
4     Marketing Analytics: Marketing Measurement Str...  Principiante   
...                                                 ...           ...   
3813   Data Representation andVisualization in Tableau…    Intermedio   
3814          Introduction to DataAnalysis using Excel…  Principiante   
3815            Statistics: Unlocking theWorld of Data…  Principiante   
3816            Biostatistics for Big DataApplications…  Principiante   
3817                        Essentials of DataLiteracy…  Principiante   

             course_effort  course_length(Weeks) language  price(USD)  \
0       2–3 hours per week                     2   Ingles        49.0   
1       2–4 hours per week                     7   Ingles        49.0   
2      6–18 hours per week                    12   Ingles        90.0   
3     10–15 hours per week                    13   Ingles       199.0   
4       5–7 hours per week                     4   Ingles       249.0   
...                    ...                   ...      ...         ...   
3813    6–8 hours per week                     4   Ingles       249.0   
3814    2–4 hours per week                     4   Ingles        99.0   
3815    4–6 hours per week                     8   Ingles        49.0   
3816    2–3 hours per week                     8   Ingles        49.0   
3817  10–20 hours per week                     4   Ingles        99.0   

                                 institution  n_enrolled  
0                                        edX      124980  
1                 The University of Michigan      293864  
2                         Harvard University     2442271  
3      Massachusetts Institute of Technology      129555  
4         University of California, Berkeley       81140  
...                                      ...         ...  
3813       Rochester Institute of Technology       45365  
3814                               Microsoft       45365  
3815             The University of Edinburgh       45365  
3816  The University of Texas Medical Branch       45365  
3817                        Davidson College       45365  

[3816 rows x 8 columns]

In [324]:
#Vamos a cambiar el nombre de las columnas a nombres en español
df_edx_join.rename(columns={'title': 'nombre_curso', 'Level': 'nivel_del_curso', 'course_effort': 'horas_dedicadas', 'course_length(Weeks)': 'duracion_del_curso(Semanas)', 'language': 'lenguaje', 'price(USD)': 'precio(USD)', 'institution': 'organizacion', 'n_enrolled': 'cant_estudiantes'}, inplace=True)


In [325]:
df_edx_join.head(3)

nombre_curso nivel_del_curso  \
0                                How to Learn Online    Principiante   
1  Programming for Everybody (Getting Started wit...    Principiante   
2            CS50's Introduction to Computer Science    Principiante   

       horas_dedicadas  duracion_del_curso(Semanas) lenguaje  precio(USD)  \
0   2–3 hours per week                            2   Ingles         49.0   
1   2–4 hours per week                            7   Ingles         49.0   
2  6–18 hours per week                           12   Ingles         90.0   

                 organizacion  cant_estudiantes  
0                         edX            124980  
1  The University of Michigan            293864  
2          Harvard University           2442271

3.- EXPORTAMOS EN NUEVOS ARCHIVOS LOS DATAFRAMES OBTENIDOS

In [326]:
df_edx_join.to_csv('dataEDXcompleta.csv', index=False)

#### C. COMENZAREMOS CON LA LIMPIEZA DE LOS DATOS CORRESPONDIENTES A LA EMPRESA UDEMY

1- IMPORTANTE:
                 Vamos a prescindir de utilizar la data proporcionada por la dirección debido a que esta no cuenta con un dato importante como es el la valoración del curso, por lo que prescindiremos del uso de esta data ya que tenemos otra data con la misma información proporcionada en la data de la direccion pero adicionalmente contamos con la valoración para cada curso.

OBS: Además de la data proporcionada por la dirección adicionalmente utilizaremos otros conjuntos de datos obtenidos del sitio de bases de datos públicos de Kaggle para obtener un conjunto de datos más robusto con el que podamos realizar un análisis de datos mas profundo.

2- IMPORTAMOS LA DATA DE NOMBRE 3.1-data-sheet-udemy-courses-business-courses.csv

In [4]:
#Creamos un dataframe
df_udemy2 = pd.read_csv('./Datos adicionales/udemy/3.1-data-sheet-udemy-courses-business-courses.csv', sep=',')

In [40]:
#Visualizamos
df_udemy2.head()

course_id                                       course_title  \
0    49798.0  Bitcoin or How I Learned to Stop Worrying and ...   
1    48841.0    Accounting in 60 Minutes - A Brief Introduction   
2   133536.0               Stock Market Investing for Beginners   
3   151668.0                 Introduction to Financial Modeling   
4   648826.0         The Complete Financial Analyst Course 2017   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/bitcoin-or-how-i-learned...    0.0          65576.0   
1  https://www.udemy.com/accounting-in-60-minutes...    0.0          56659.0   
2  https://www.udemy.com/the-beginners-guide-to-t...    0.0          50855.0   
3  https://www.udemy.com/financial-modeling-asimp...    0.0          29167.0   
4  https://www.udemy.com/the-complete-financial-a...  195.0          24481.0   

   num_reviews  num_lectures           level  Rating  content_duration  \
0        936.0          24.0      All Levels    0.56               8.0   
1       4397.0          16.0  Beginner Level    0.95               1.5   
2       2698.0          15.0      All Levels    0.91               1.5   
3       1463.0           8.0      All Levels    0.18               1.5   
4       2347.0         174.0      All Levels    0.37              10.0   

    published_timestamp           subject  
0  2013-04-20T02:25:22Z  Business Finance  
1  2013-04-07T21:39:25Z  Business Finance  
2  2013-12-25T19:53:34Z  Business Finance  
3  2014-05-27T16:22:16Z  Business Finance  
4  2016-01-21T01:38:48Z  Business Finance

3- IMPORTAMOS LA DATA DE NOMBRE 3.1-data-sheet-udemy-courses-design-courses.csv

In [6]:
#Creamos un dataframe
df_udemy3 = pd.read_csv('./Datos adicionales/udemy/3.1-data-sheet-udemy-courses-design-courses.csv', sep=',')

In [39]:
#Visualizamos
df_udemy3.head()

course_id                                       course_title  \
0   348116.0  Photoshop In-Depth: Master all of Photoshop's ...   
1    17349.0  Figure Drawing From Life Using The Reilly Tech...   
2   399938.0      Professional Logo Design in Adobe Illustrator   
3   820194.0  Photoshop for Entrepreneurs - Design 11 Practi...   
4   249126.0                             Logo Design Essentials   

                                                 url  price  num_subscribers  \
0             https://www.udemy.com/photoshop-tools/    0.0          53851.0   
1  https://www.udemy.com/figure-drawing-from-life...    0.0          47811.0   
2  https://www.udemy.com/professional-logo-design...    0.0          44044.0   
3  https://www.udemy.com/photoshop-for-entreprene...  200.0          36288.0   
4                 https://www.udemy.com/logo-design/   20.0          33205.0   

   num_reviews  num_lectures           level  Rating  content_duration  \
0       1779.0          45.0      All Levels    0.69               4.5   
1       1041.0          22.0  Beginner Level    0.11               2.5   
2       1563.0          45.0  Beginner Level    0.89               7.5   
3        737.0          63.0      All Levels    0.96               5.0   
4        481.0          12.0  Beginner Level    0.88               0.7   

    published_timestamp         subject  
0  2014-11-30T04:22:11Z  Graphic Design  
1  2012-05-09T18:14:57Z  Graphic Design  
2  2015-01-22T11:18:06Z  Graphic Design  
3  2016-06-09T01:57:03Z  Graphic Design  
4  2014-06-30T03:09:27Z  Graphic Design

4- IMPORTAMOS LA DATA DEL ARCHIVO DE NOMBRE 3.1-data-sheet-udemy-courses-music-courses.csv

In [8]:
#Creamos un dataframe
df_udemy4 = pd.read_csv('./Datos adicionales/udemy/3.1-data-sheet-udemy-courses-music-courses.csv', sep=',')

In [38]:
#Visualizamos
df_udemy4.head()

course_id                                       course_title  \
0      19421              Free Beginner Electric Guitar Lessons   
1     238934  Pianoforall - Incredible New Way To Learn Pian...   
2      41884                Getting Started with Playing Guitar   
3      42271      Complete Guitar System - Beginner to Advanced   
4      26956                            Learn Guitar in 21 Days   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/beginner-electric-guitar...      0           101154   
1  https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2  https://www.udemy.com/getting-started-with-pla...      0            47652   
3  https://www.udemy.com/complete-guitar-system-b...    145            32935   
4     https://www.udemy.com/learn-guitar-in-21-days/     20            26504   

   num_reviews  num_lectures           level  Rating  content_duration  \
0         1042            95      All Levels    0.88               4.5   
1         7676           362  Beginner Level    0.96              30.0   
2         1141            26      All Levels    0.68               4.0   
3         2713           310      All Levels    0.65              34.0   
4          192            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

5- IMPORTAMOS LA DATA DE NOMBRE 3.1-data-sheet-udemy-courses-web-development.csv

In [10]:
#Creamos un dataframe
df_udemy5 = pd.read_csv('./Datos adicionales/udemy/3.1-data-sheet-udemy-courses-web-development.csv', sep=',')

In [37]:
#Visualizamos
df_udemy5.head()

course_id                                       course_title  \
0    41295.0               Learn HTML5 Programming From Scratch   
1    59014.0                     Coding for Entrepreneurs Basic   
2   625204.0                         The Web Developer Bootcamp   
3   173548.0  Build Your First Website in 1 Week with HTML5 ...   
4   764164.0              The Complete Web Developer Course 2.0   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/learn-html5-programming-...    0.0         268923.0   
1  https://www.udemy.com/coding-for-entrepreneurs...    0.0         161029.0   
2  https://www.udemy.com/the-web-developer-bootcamp/  200.0         121584.0   
3  https://www.udemy.com/build-your-first-website...    0.0         120291.0   
4  https://www.udemy.com/the-complete-web-develop...  200.0         114512.0   

   num_reviews  num_lectures           level  Rating  content_duration  \
0       8629.0          45.0  Beginner Level    0.82              10.5   
1        279.0          27.0    Expert Level    0.69               3.5   
2      27445.0         342.0  Beginner Level    0.89              43.0   
3       5924.0          30.0      All Levels    0.78               3.0   
4      22412.0         304.0  Beginner Level    0.55              30.5   

    published_timestamp                   subject  
0  2013-02-14T07:03:41Z  Subject: Web Development  
1  2013-06-09T15:51:55Z  Subject: Web Development  
2  2015-11-02T21:13:27Z  Subject: Web Development  
3  2014-04-08T16:21:30Z  Subject: Web Development  
4  2016-03-08T22:28:36Z  Subject: Web Development

6.- VAMOS A UNIR LOS DATAFRAMES QUE TIENEN TODAS LAS COLUMNAS EN COMÚN

In [76]:
#Vamos a unir nuestros dataframes df_udemy2, df_udemy3, df_udemy4, df_udemy5
df_concatenado = pd.concat([df_udemy2, df_udemy3, df_udemy4, df_udemy5], ignore_index=True)


In [77]:
#Visualizamos 
df_concatenado

course_id                                       course_title  \
0       49798.0  Bitcoin or How I Learned to Stop Worrying and ...   
1       48841.0    Accounting in 60 Minutes - A Brief Introduction   
2      133536.0               Stock Market Investing for Beginners   
3      151668.0                 Introduction to Financial Modeling   
4      648826.0         The Complete Financial Analyst Course 2017   
...         ...                                                ...   
3676  1227578.0           Learning Path: The Road to Elasticsearch   
3677  1277924.0                            Angular 4 Front To Back   
3678  1248172.0            Essentials of Spring 5.0 for Developers   
3679  1250934.0  Display and analyze GIS data on the web with L...   
3680  1270222.0  Learning Path: Web Applications with Spring an...   

                                                    url  price  \
0     https://www.udemy.com/bitcoin-or-how-i-learned...    0.0   
1     https://www.udemy.com/accounting-in-60-minutes...    0.0   
2     https://www.udemy.com/the-beginners-guide-to-t...    0.0   
3     https://www.udemy.com/financial-modeling-asimp...    0.0   
4     https://www.udemy.com/the-complete-financial-a...  195.0   
...                                                 ...    ...   
3676  https://www.udemy.com/learning-path-the-road-t...  200.0   
3677     https://www.udemy.com/angular-4-front-to-back/   40.0   
3678  https://www.udemy.com/essentials-of-spring-50-...  125.0   
3679  https://www.udemy.com/display-and-analyze-gis-...  100.0   
3680  https://www.udemy.com/learning-path-web-applic...  200.0   

      num_subscribers  num_reviews  num_lectures           level  Rating  \
0             65576.0        936.0          24.0      All Levels    0.56   
1             56659.0       4397.0          16.0  Beginner Level    0.95   
2             50855.0       2698.0          15.0      All Levels    0.91   
3             29167.0       1463.0           8.0      All Levels    0.18   
4             24481.0       2347.0         174.0      All Levels    0.37   
...               ...          ...           ...             ...     ...   
3676             50.0          5.0          60.0  Beginner Level    0.96   
3677             44.0          0.0          68.0      All Levels    0.15   
3678             34.0          2.0          21.0  Beginner Level    0.46   
3679             25.0          4.0          66.0  Beginner Level    0.67   
3680             19.0          2.0          33.0  Beginner Level    0.12   

      content_duration   published_timestamp                   subject  
0                  8.0  2013-04-20T02:25:22Z          Business Finance  
1                  1.5  2013-04-07T21:39:25Z          Business Finance  
2                  1.5  2013-12-25T19:53:34Z          Business Finance  
3                  1.5  2014-05-27T16:22:16Z          Business Finance  
4                 10.0  2016-01-21T01:38:48Z          Business Finance  
...                ...                   ...                       ...  
3676               5.0  2017-05-29T17:56:24Z  Subject: Web Development  
3677               8.5  2017-07-06T15:04:55Z  Subject: Web Development  
3678               1.5  2017-06-11T18:34:40Z  Subject: Web Development  
3679              12.5  2017-06-15T21:17:43Z  Subject: Web Development  
3680               4.0  2017-06-28T21:04:21Z  Subject: Web Development  

[3681 rows x 12 columns]

In [78]:
#Vamos a crear una nueva columna de nombre Free/Paid y para esto debemos definir una funcion que nos ayude
# Definir una función para aplicar la lógica de marcado "Free/Paid"
def marca_free_paid(valor):
    if valor > 0:
        return "Paid"
    else:
        return "Free"

In [79]:
# Aplicamos la función a la columna "price" para crear la columna "Free/Paid"
df_concatenado['Free/Paid'] = df_concatenado['price'].apply(marca_free_paid)

In [80]:
#Visualizamos
df_concatenado

course_id                                       course_title  \
0       49798.0  Bitcoin or How I Learned to Stop Worrying and ...   
1       48841.0    Accounting in 60 Minutes - A Brief Introduction   
2      133536.0               Stock Market Investing for Beginners   
3      151668.0                 Introduction to Financial Modeling   
4      648826.0         The Complete Financial Analyst Course 2017   
...         ...                                                ...   
3676  1227578.0           Learning Path: The Road to Elasticsearch   
3677  1277924.0                            Angular 4 Front To Back   
3678  1248172.0            Essentials of Spring 5.0 for Developers   
3679  1250934.0  Display and analyze GIS data on the web with L...   
3680  1270222.0  Learning Path: Web Applications with Spring an...   

                                                    url  price  \
0     https://www.udemy.com/bitcoin-or-how-i-learned...    0.0   
1     https://www.udemy.com/accounting-in-60-minutes...    0.0   
2     https://www.udemy.com/the-beginners-guide-to-t...    0.0   
3     https://www.udemy.com/financial-modeling-asimp...    0.0   
4     https://www.udemy.com/the-complete-financial-a...  195.0   
...                                                 ...    ...   
3676  https://www.udemy.com/learning-path-the-road-t...  200.0   
3677     https://www.udemy.com/angular-4-front-to-back/   40.0   
3678  https://www.udemy.com/essentials-of-spring-50-...  125.0   
3679  https://www.udemy.com/display-and-analyze-gis-...  100.0   
3680  https://www.udemy.com/learning-path-web-applic...  200.0   

      num_subscribers  num_reviews  num_lectures           level  Rating  \
0             65576.0        936.0          24.0      All Levels    0.56   
1             56659.0       4397.0          16.0  Beginner Level    0.95   
2             50855.0       2698.0          15.0      All Levels    0.91   
3             29167.0       1463.0           8.0      All Levels    0.18   
4             24481.0       2347.0         174.0      All Levels    0.37   
...               ...          ...           ...             ...     ...   
3676             50.0          5.0          60.0  Beginner Level    0.96   
3677             44.0          0.0          68.0      All Levels    0.15   
3678             34.0          2.0          21.0  Beginner Level    0.46   
3679             25.0          4.0          66.0  Beginner Level    0.67   
3680             19.0          2.0          33.0  Beginner Level    0.12   

      content_duration   published_timestamp                   subject  \
0                  8.0  2013-04-20T02:25:22Z          Business Finance   
1                  1.5  2013-04-07T21:39:25Z          Business Finance   
2                  1.5  2013-12-25T19:53:34Z          Business Finance   
3                  1.5  2014-05-27T16:22:16Z          Business Finance   
4                 10.0  2016-01-21T01:38:48Z          Business Finance   
...                ...                   ...                       ...   
3676               5.0  2017-05-29T17:56:24Z  Subject: Web Development   
3677               8.5  2017-07-06T15:04:55Z  Subject: Web Development   
3678               1.5  2017-06-11T18:34:40Z  Subject: Web Development   
3679              12.5  2017-06-15T21:17:43Z  Subject: Web Development   
3680               4.0  2017-06-28T21:04:21Z  Subject: Web Development   

     Free/Paid  
0         Free  
1         Free  
2         Free  
3         Free  
4         Paid  
...        ...  
3676      Paid  
3677      Paid  
3678      Paid  
3679      Paid  
3680      Paid  

[3681 rows x 13 columns]

In [81]:
#Creamos una nueva columna a nuestra data a partir de los 10 primeros caracteres de nuestra columna published_timestamp
df_concatenado['Date'] = df_concatenado['published_timestamp'].str.slice(0, 10)

In [82]:
#Visualizamos
df_concatenado.head()

course_id                                       course_title  \
0    49798.0  Bitcoin or How I Learned to Stop Worrying and ...   
1    48841.0    Accounting in 60 Minutes - A Brief Introduction   
2   133536.0               Stock Market Investing for Beginners   
3   151668.0                 Introduction to Financial Modeling   
4   648826.0         The Complete Financial Analyst Course 2017   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/bitcoin-or-how-i-learned...    0.0          65576.0   
1  https://www.udemy.com/accounting-in-60-minutes...    0.0          56659.0   
2  https://www.udemy.com/the-beginners-guide-to-t...    0.0          50855.0   
3  https://www.udemy.com/financial-modeling-asimp...    0.0          29167.0   
4  https://www.udemy.com/the-complete-financial-a...  195.0          24481.0   

   num_reviews  num_lectures           level  Rating  content_duration  \
0        936.0          24.0      All Levels    0.56               8.0   
1       4397.0          16.0  Beginner Level    0.95               1.5   
2       2698.0          15.0      All Levels    0.91               1.5   
3       1463.0           8.0      All Levels    0.18               1.5   
4       2347.0         174.0      All Levels    0.37              10.0   

    published_timestamp           subject Free/Paid        Date  
0  2013-04-20T02:25:22Z  Business Finance      Free  2013-04-20  
1  2013-04-07T21:39:25Z  Business Finance      Free  2013-04-07  
2  2013-12-25T19:53:34Z  Business Finance      Free  2013-12-25  
3  2014-05-27T16:22:16Z  Business Finance      Free  2014-05-27  
4  2016-01-21T01:38:48Z  Business Finance      Paid  2016-01-21

In [22]:
#Cambiamos el nombre a la columna Rating
#df_concatenado.rename(columns=({'Rating': 'rating'}), inplace=True)

OBS: Ahora que tenemos nuestro dataframe completo comenzaremos con la limpieza de este dataframe.

In [83]:
#Veamos la información de los datos
df_concatenado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3681 entries, 0 to 3680
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object 
 2   url                  3676 non-null   object 
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object 
 8   Rating               3677 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   object 
 11  subject              3677 non-null   object 
 12  Free/Paid            3681 non-null   object 
 13  Date                 3676 non-null   object 
dtypes: float64(7), object(7)
memory usage: 402.7+ KB


In [84]:
#Contabilizamos los nulos
df_concatenado.isnull().sum()

course_id              5
course_title           5
url                    5
price                  5
num_subscribers        5
num_reviews            5
num_lectures           5
level                  5
Rating                 4
content_duration       5
published_timestamp    5
subject                4
Free/Paid              0
Date                   5
dtype: int64

In [85]:
#Veamos la cantidad de duplicados
df_concatenado.duplicated().value_counts()

False    3679
True        2
dtype: int64

In [86]:
#Veamos los valores en la columna level
df_concatenado['level'].value_counts()

All Levels            1925
Beginner Level        1271
Intermediate Level     422
Expert Level            58
Name: level, dtype: int64

In [87]:
#Veamos los valores en la columna level
df_concatenado['subject'].value_counts()

Subject: Web Development    1204
Business Finance            1191
Musical Instruments          680
Graphic Design               602
Name: subject, dtype: int64

OBS: En una primera inspección de los datos vemos que algunas columnas no son necesarias para nuestro analisis, tenemos pocos valores nulos que procederemos a eliminar, algunas columnas no tienen el tipo de dato correcto, la columna rating tiene valores menores a uno, solo tenemos 2 columnas duplicadas, los valores en la columna level estan en ingles así como también de la columna subject.

In [88]:
#Eliminaremos algunas columnas
df_concatenado.drop(columns=['course_id', 'url', 'published_timestamp'], inplace=True)

In [89]:
df_concatenado

course_title  price  \
0     Bitcoin or How I Learned to Stop Worrying and ...    0.0   
1       Accounting in 60 Minutes - A Brief Introduction    0.0   
2                  Stock Market Investing for Beginners    0.0   
3                    Introduction to Financial Modeling    0.0   
4            The Complete Financial Analyst Course 2017  195.0   
...                                                 ...    ...   
3676           Learning Path: The Road to Elasticsearch  200.0   
3677                            Angular 4 Front To Back   40.0   
3678            Essentials of Spring 5.0 for Developers  125.0   
3679  Display and analyze GIS data on the web with L...  100.0   
3680  Learning Path: Web Applications with Spring an...  200.0   

      num_subscribers  num_reviews  num_lectures           level  Rating  \
0             65576.0        936.0          24.0      All Levels    0.56   
1             56659.0       4397.0          16.0  Beginner Level    0.95   
2             50855.0       2698.0          15.0      All Levels    0.91   
3             29167.0       1463.0           8.0      All Levels    0.18   
4             24481.0       2347.0         174.0      All Levels    0.37   
...               ...          ...           ...             ...     ...   
3676             50.0          5.0          60.0  Beginner Level    0.96   
3677             44.0          0.0          68.0      All Levels    0.15   
3678             34.0          2.0          21.0  Beginner Level    0.46   
3679             25.0          4.0          66.0  Beginner Level    0.67   
3680             19.0          2.0          33.0  Beginner Level    0.12   

      content_duration                   subject Free/Paid        Date  
0                  8.0          Business Finance      Free  2013-04-20  
1                  1.5          Business Finance      Free  2013-04-07  
2                  1.5          Business Finance      Free  2013-12-25  
3                  1.5          Business Finance      Free  2014-05-27  
4                 10.0          Business Finance      Paid  2016-01-21  
...                ...                       ...       ...         ...  
3676               5.0  Subject: Web Development      Paid  2017-05-29  
3677               8.5  Subject: Web Development      Paid  2017-07-06  
3678               1.5  Subject: Web Development      Paid  2017-06-11  
3679              12.5  Subject: Web Development      Paid  2017-06-15  
3680               4.0  Subject: Web Development      Paid  2017-06-28  

[3681 rows x 11 columns]

In [90]:
#Cambiaremos los valores de la columna level
df_concatenado['level'] = df_concatenado['level'].str.replace('Beginner Level', 'Principiante')
df_concatenado['level'] = df_concatenado['level'].str.replace('Intermediate Level', 'Intermedio')
df_concatenado['level'] = df_concatenado['level'].str.replace('Expert Level', 'Avanzado')
df_concatenado['level'] = df_concatenado['level'].str.replace('All Levels', 'Mixto')

In [91]:
#Cambiaremos los valores de la columna subject
df_concatenado['subject'] = df_concatenado['subject'].str.replace('Subject: Web Development', 'Desarrollo web')
df_concatenado['subject'] = df_concatenado['subject'].str.replace('Business Finance', 'Negocios y Finanzas')
df_concatenado['subject'] = df_concatenado['subject'].str.replace('Musical Instruments', 'Instrumentos musicales')
df_concatenado['subject'] = df_concatenado['subject'].str.replace('Graphic Design', 'Diseño grafico')

In [93]:
#Multiplicaremos la columna rating por 5 para obtener un valor decimal con parte entera
df_concatenado['Rating'] = df_concatenado['Rating']*5

In [94]:
df_concatenado.head()

course_title  price  num_subscribers  \
0  Bitcoin or How I Learned to Stop Worrying and ...    0.0          65576.0   
1    Accounting in 60 Minutes - A Brief Introduction    0.0          56659.0   
2               Stock Market Investing for Beginners    0.0          50855.0   
3                 Introduction to Financial Modeling    0.0          29167.0   
4         The Complete Financial Analyst Course 2017  195.0          24481.0   

   num_reviews  num_lectures         level  Rating  content_duration  \
0        936.0          24.0         Mixto    2.80               8.0   
1       4397.0          16.0  Principiante    4.75               1.5   
2       2698.0          15.0         Mixto    4.55               1.5   
3       1463.0           8.0         Mixto    0.90               1.5   
4       2347.0         174.0         Mixto    1.85              10.0   

               subject Free/Paid        Date  
0  Negocios y Finanzas      Free  2013-04-20  
1  Negocios y Finanzas      Free  2013-04-07  
2  Negocios y Finanzas      Free  2013-12-25  
3  Negocios y Finanzas      Free  2014-05-27  
4  Negocios y Finanzas      Paid  2016-01-21

In [95]:
#Eliminaremos los nulos
df_concatenado.dropna(inplace=True)

In [96]:
#Asignaremos el tipo de dato a las columnas
df_concatenado['num_subscribers'] = df_concatenado['num_subscribers'].astype(int)
df_concatenado['num_reviews'] = df_concatenado['num_reviews'].astype(int)
df_concatenado['num_lectures'] = df_concatenado['num_lectures'].astype(int)
df_concatenado['Date'] = df_concatenado['Date'].astype('datetime64[ns]')

In [97]:
#Veamos la informacion de los datos
df_concatenado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3676 entries, 0 to 3680
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   course_title      3676 non-null   object        
 1   price             3676 non-null   float64       
 2   num_subscribers   3676 non-null   int32         
 3   num_reviews       3676 non-null   int32         
 4   num_lectures      3676 non-null   int32         
 5   level             3676 non-null   object        
 6   Rating            3676 non-null   float64       
 7   content_duration  3676 non-null   float64       
 8   subject           3676 non-null   object        
 9   Free/Paid         3676 non-null   object        
 10  Date              3676 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int32(3), object(4)
memory usage: 301.5+ KB


In [99]:
#Cambiamos el nombre de las columnas
df_concatenado.rename(columns={'course_title':'nombre_curso', 'price':'price(USD)', 'num_subscribers':'cant_suscriptores', 'num_reviews':'cant_opiniones', 'num_lectures':'cant_lecciones', 'level':'nivel', 'Rating':'valoracion', 'content_duration':'duracion_curso', 'subject':'categoria', 'Date':'fecha_curso'}, inplace=True)

In [101]:
#Crearemos una columna con el año de lanzamiento del curso a partir de la columna fecha_curso
df_concatenado['año'] = df_concatenado['fecha_curso'].dt.year

In [102]:
#Visualizamos
df_concatenado.head()

nombre_curso  price(USD)  \
0     Bitcoin or How I Learned to Stop Worrying and ...         0.0   
1       Accounting in 60 Minutes - A Brief Introduction         0.0   
2                  Stock Market Investing for Beginners         0.0   
3                    Introduction to Financial Modeling         0.0   
4            The Complete Financial Analyst Course 2017       195.0   
...                                                 ...         ...   
3676           Learning Path: The Road to Elasticsearch       200.0   
3677                            Angular 4 Front To Back        40.0   
3678            Essentials of Spring 5.0 for Developers       125.0   
3679  Display and analyze GIS data on the web with L...       100.0   
3680  Learning Path: Web Applications with Spring an...       200.0   

      cant_suscriptores  cant_opiniones  cant_lecciones         nivel  \
0                 65576             936              24         Mixto   
1                 56659            4397              16  Principiante   
2                 50855            2698              15         Mixto   
3                 29167            1463               8         Mixto   
4                 24481            2347             174         Mixto   
...                 ...             ...             ...           ...   
3676                 50               5              60  Principiante   
3677                 44               0              68         Mixto   
3678                 34               2              21  Principiante   
3679                 25               4              66  Principiante   
3680                 19               2              33  Principiante   

      valoracion  duracion_curso            categoria Free/Paid fecha_curso  \
0           2.80             8.0  Negocios y Finanzas      Free  2013-04-20   
1           4.75             1.5  Negocios y Finanzas      Free  2013-04-07   
2           4.55             1.5  Negocios y Finanzas      Free  2013-12-25   
3           0.90             1.5  Negocios y Finanzas      Free  2014-05-27   
4           1.85            10.0  Negocios y Finanzas      Paid  2016-01-21   
...          ...             ...                  ...       ...         ...   
3676        4.80             5.0       Desarrollo web      Paid  2017-05-29   
3677        0.75             8.5       Desarrollo web      Paid  2017-07-06   
3678        2.30             1.5       Desarrollo web      Paid  2017-06-11   
3679        3.35            12.5       Desarrollo web      Paid  2017-06-15   
3680        0.60             4.0       Desarrollo web      Paid  2017-06-28   

       año  
0     2013  
1     2013  
2     2013  
3     2014  
4     2016  
...    ...  
3676  2017  
3677  2017  
3678  2017  
3679  2017  
3680  2017  

[3676 rows x 12 columns]

7.- EXPORTAMOS NUESTRO DATAFRAME

In [103]:
df_concatenado.to_csv('dataudemycompleta.csv', index=False)